### ISSUE TITLE
New Column Container

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1013]
Create a column container that can bundle different column classes and present it as a single column in the interface.

**Comment by JoryHogeveen** [comment]
> bundle different column classes

You mean a column for a single field column classes string?
If so, please see the Genesis addon, already done in there and will handle filter/sort as well.

**Comment by tobiasschutter** [comment]
Hi Jory, I couldn't find a solution for this issue in your genesis add-on. I think we have a different problem. We are going to bundle **different** column classes together. This will allow the user to switch between columns using a select field setting.

**Comment by JoryHogeveen** [comment]
Ah, yeah that is something different! I thought it was about the contents of a column (textfield for css classes). Nvm then!
