### ISSUE TITLE
Support filtering and sorting for Taxonomy overviews

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1030]
Reevaluate filtering and sorting for taxonomies.
We did not have a look at this since WP support their own wp_termmeta table

Update:
- [x] Filtering support for Taxonomies
- [x] Sorting support for Taxonomies

Example Columns
**ID**
- [x] Sortable
- [x] Filterable

**Custom Field**
- [x] Sortable
- [x] Filterable

**Comment by DGStefan** [comment]
@davidmosterd 
Could you have a look at this? There are new sorting and filtering strategies for Taxonomy. It's difficult to determine the main query in this overview. Maybe you can think of a better way to determine this.

**Comment by tobiasschutter** [comment]
https://github.com/codepress/admin-columns-pro/pull/235
