### ISSUE TITLE
Delegated Filtering models show their shadow filter drop down for a moment

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1032]
Reproduce:
Add the category column to the posts overview and enable filtering. When you go to the overview page you see the original category filter drop down and for a few seconds the empty drop down added by Admin Columns. It shoud not show the Admin Columns drop down when a filter model is delegated to it's default WordPress filter.

**Comment by davidmosterd** [comment]
Fix written on AC, ACP and CAC dev
