### ISSUE TITLE
Set expiration in seconds per filter for dropdown cache

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#1035]
Some dropdowns are really heavy to cache and don't change a lot, so setting a longer expiration or manual expiration could help.

**Comment by davidmosterd** [comment]
Issue has been resolved but required quite a refactor of how caching, table screens and the filtering models. So it requires some thorough testing before we merge this into develop.

**Comment by DGStefan** [comment]
- [x] Ajax update scripts don't work
