### ISSUE TITLE
Add context to translation strings

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#1050]
From Transifex comment: I believe this 'From' here means the original price, or maybe the initial date, but this word can also be used to indicate the sender of an e-mail. Please always add the context in each case to avoid mistaken translations.

source: https://www.transifex.com/codepress/admin-columns-pro/translate/#pt_BR/codepress-admin-columns/132850727

**Comment by DGStefan** [comment]
@tobiasschutter 
Let's try to make this a way of work in stead of trying to find each translation that needs a context.
I've changed this specific translation along with the same translations in the same file that are quite similar.
