### ISSUE TITLE
Reset sorting does not work on users

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#1054]
sorted users on LTV on ac.com, then tried "reset sorting preference".

**Comment by DGStefan** [comment]
@tobiasschutter 
I looked at the code and in the database and all sorting preferences are removed correctly. I believe it has something to do with object caching in WPEngine. When you logout and login again, the overview is as it should be. 

I cannot reproduce the issue on a local environment. Can we close this ticket?
