### ISSUE TITLE
Time picker on Types Date fields

### ISSUE THREAD

**Issue by scheldejonas** [codepress/admin-columns-issues#1055]
Hello AdminColumns

If had an issue, missing the time picker also on Toolset Types Date Fields.

The case is you can choose both only date but also date/time, when you are creating the field in Types interface.

So this if statement is not solved in my fix, but I thought to give you my fix, to make it work anyway.

******
<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class ACA_Types_Editing_Date extends ACA_Types_Editing {

	public function get_view_settings() {
		$data = parent::get_view_settings();

		$data['type'] = 'date_time';

		return $data;
	}

	public function get_edit_value( $id ) {
		$timestamp = parent::get_edit_value( $id );

		if ( ! $timestamp ) {
			return false;
		}

		// Single. Format for datepicker.
		return date( 'Y-m-d h:i:s', $timestamp );
	}

	/**
	 * Store as timestamp
	 *
	 * @param int    $id
	 * @param string $value
	 */
	public function save( $id, $value ) {
		parent::save( $id, strtotime( $value ) );
	}

}
****

**Comment by DGStefan** [comment]
@scheldejonas 
You snippet is missing, but I suppose you're talking about the inline edit feature here right?
I will try to reproduce it with the Toolset Types and make the changes necessary.
We already have date time support for inline edit, so it would not be that difficult to make it work.
Thank you very much for your input!

**Comment by DGStefan** [comment]
@scheldejonas 
Thanks for your feedback.
I've changed this in the code for our Toolset Types integration and it will be available for the next release of the Toolset Types integration.

I've changed the code a little bit so it only offers time editing when this option is set in Types.
