### ISSUE TITLE
[i18n] Strings not getting translated

### ISSUE THREAD

**Issue by pedro-mendonca** [codepress/admin-columns-issues#1070]
Hi,

I've found some i18n issues in some strings that are wrapped in complete gettext functions, but still don't get translated.
Examples:
- [x] **Admin Columns** tab in Settings page
- [x] **Settings** tab in Settings page
- [x] **Add-ons** tab in Settings page

I've also found some hardcoded strings and inconsistent strings that I'll make a PR to correct.

Regards

**Comment by DGStefan** [comment]
@pedro-mendonca 
Thanks for your input and pull-request.
I've merged the changes for the upcoming release.

**Comment by pedro-mendonca** [comment]
@DGStefan 
You still need to check the above checklist, it's not solved by my PR.

**Comment by pedro-mendonca** [comment]
@DGStefan 
An update. The above tabs labels (Admin Columns | Settings | Add-ons) do appear translated after the language pack is on the /wp-content/languages/plugins.
I was testing only on the /wp-content/plugins/admin-columns/languages.
Marking the checkboxes as solved.
