### ISSUE TITLE
Improved capabilities

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1073]
https://www.admincolumns.com/forums/topic/filter-for-inline-editing-capability/

Currently the inline editor button is shown depending on the users capability to edit a certain post type. While that might be enough for most cases, we do require to have a more finegrained approach. I see two options: introducing a new capability or including a filter in the capability check, so I can add my own security approach.

**Comment by tobiasschutter** [comment]
We could add a new capability for Inline Editing

**Comment by DGStefan** [comment]
New filter 'acp/horizontal_scrolling/enable' added

**Comment by tobiasschutter** [comment]
I think we should introduce more fine-grained capabilities in general. We should look into each functionality - like bulk editing, filtering, export - and see what could benefit from its own capability.

```
const INLINE_EDIT = 'admin_columns_inline_edit';
const BULK_EDIT = 'admin_columns_bulk_edit';

const EXPORT_USERS = 'admin_columns_export_users';
const EXPORT_POSTS = 'admin_columns_export_posts';
const EXPORT_MEDIA = 'admin_columns_export_media';
const EXPORT_TERMS = 'admin_columns_export_terms';
const EXPORT_COMMENTS = 'admin_columns_export_comments';
const EXPORT_OTHER = 'admin_columns_export_other';
```
