### ISSUE TITLE
Listscreen refactor

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#1083]
Refactor AC\ListScreen to CRUD

- [x] Data storage model refactor (unique DB Table or Post table)
- [ ] Create an extra new "Original" list screen when using sets for the first time
- [ ] Support older exported PHP and JSON formats
- [ ] Add option to Migrate to export ALL lists screen IDs

**Comment by davidmosterd** [comment]
After working with this branch for a while I think that we can only solve this in an elegant way if we first change the way we store the data. Right now this is done in either PHP or two separate option rows where the key contains multiple parts of information.

It has been suggested to create our own table or use the posts table to start storing list screens. I think once we have an elegant way to store the data, we can work on an elegant way to reflect this in the code.
