### ISSUE TITLE
It's not possible to  update Admin Columns Pro with wp-cli

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1087]
wp-cli does not recognize that there are updates for Admin Columns Pro and add-ons

**Assumptions**
- There must be a valid license key active

**Reproduce**
1) Install older version of Admin Columns Pro and enter license key (it will directly show that there is an update)
2) in the root folder use 'wp plugin list' > It says there is an update for Admin Columns Pro
3) It always seems to reflect the update status that is available in WordPress itself

**TODO**
- Check if we can use another hook to check for updates

**Comment by stakeworks** [comment]
WordPress management tools like Plesk WordPress Toolkit (uses wp-cli) and WP-Remote from Maekit don't recognize that there are updates for Admin Columns Pro and add-ons. Also updating through wp-cli (wp plugin update admin-columns-pro) doesn't work, .

The update notifications are only visible on the update page in WordPress.

PHP 7.0
WP-CLI 1.4.0

**Comment by tobiasschutter** [comment]
It seems fixed. I used the latest ACP 5.1.3 version, and the plugin is updated by using WP CLI.
`wp plugin update --all`
