### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1100]
Implementation of Search / Filtering V2

- [x] Inline Editing select2 resets Search filters

**Comment by tobiasschutter** [comment]
GUI issues:
- [x] Highlight filter button only when rules have been changed (check DOM when rules are applied and removed)
- [x] Remove spacing when rule list is empty
- [x] Make Select label translatable
- [x] When select has only one option we can either remove the arrow or just show the label
- [x] When only one filter type is available pre-select the first type
- [x] Dropdown stays in the screen when its open and remove has been clicked
- [x] Fade the background when there is an error (e.g. empty value field)
- [x] Closes other rules when a new one is added
- [x] Clicking outside the select 2 drop-down menu should close it

Could you look at these @DGStefan ?
