### ISSUE TITLE
 ‘numeric’ is a reserved keyword as of PHP version 7.0

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1116]
'Numeric' is marked as a soft reserved keyword.
http://php.net/manual/en/reserved.other-reserved-words.php

---

FILE: /home/utilarea/public_html/wordpress/wp-content/plugins/admin-columns-pro/classes/Editing/classes/Model/CustomField/Numeric.php
7 | ERROR | ‘numeric’ is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_CLASS)

---

FILE: /home/utilarea/public_html/wordpress/wp-content/plugins/admin-columns-pro/classes/Sorting/classes/Model/CustomField/Numeric.php
8 | ERROR | ‘numeric’ is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_CLASS)

---

FILE: /home/utilarea/public_html/wordpress/wp-content/plugins/admin-columns-pro/classes/Filtering/classes/Model/CustomField/Numeric.php
7 | ERROR | ‘numeric’ is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_CLASS)

**Comment by tobiasschutter** [comment]
Fixed
