### ISSUE TITLE
Notice: AC_Column_CustomField is a deprecated class since version 4.3!

### ISSUE THREAD

**Issue by JoryHogeveen** [codepress/admin-columns-issues#1117]
Notice: AC_Column_CustomField is a deprecated class since version 4.3! Use AC\Column\CustomField instead. in /wp-content/plugins/codepress-admin-columns/classes/Autoloader/Underscore.php on line 132

Field settings:
![image](https://user-images.githubusercontent.com/826148/42944541-3412eab6-8b66-11e8-88ba-9d8f3e5bdcd8.png)

**Comment by DGStefan** [comment]
@JoryHogeveen 
I'm not able to reproduce this issue on our latest version of Free and Pro.
I expect you have a reference to 'AC_Column_CustomField' in your own code/plugin that must be updated to the namespaced version. Can you check to be sure and let me know if we can close this ticket?

**Comment by JoryHogeveen** [comment]
@DGStefan 
I found the issue, it's a compat function of mine that was still using the old code.
Weird though, it only happened in one since column of one row.. the same column in other rows work fine..
