### ISSUE TITLE
Uncaught Error: Class 'AC\Admin\Addon\._[Types / WooCommerce / etc]' not found

### ISSUE THREAD

**Issue by wiiiimm** [codepress/admin-columns-issues#1119]
I am using admin-columns-issues in a Wordpress that runs inside a Docker container.

The whole wp-content folder is deployed to Docker via a script that uses tar

```
mkdir -p deploy && cp -R wp-content deploy && rm -rf deploy/wp-content/.git && chmod -R 755 deploy/wp-content && rm -rf deploy/wp-content/cache && tar -pcvzf deploy/payload.tar.gz -C deploy wp-content
```

and is added to Docker with

```
ADD deploy/* /var/www/html/
```

For some strange reason, I will run into various Class not found when the code is deployed into the docker container like this.

The error will not occur if I map a local volume directly to the docker container.

If I reinstall the admin-columns plugin inside the docker container, the problem also goes away.
I use diff to compare the original folder with the one extracted from the tar file and could not find any missing files...

Right now I have restored to manually reinstalling the admin-columns plugin during docker deployment.

**Comment by DGStefan** [comment]
@williamli 
I'm not sure how I can reproduce this issue.
But we use an Autoloader to load the classes necessary.
Based on the error, I expect that the file `admin-columns-pro\admin-columns\classes\Admin\Addon\Types.php` does not exists. 

Although you said that there were no files are missing when you run a diff, can you check this just to be sure? If the files are already there, does it change when you re-copy these specific files to that location?

**Comment by wiiiimm** [comment]
The files are indeed there.

**Comment by wiiiimm** [comment]
@DGStefan do you think sharing the same wordpress database from my local dev server with the production server (via export and import) can cause this issue with your plugin?

**Comment by wiiiimm** [comment]
@DGStefan what is the expected file permission / content of ._Types.php and ._WooCommerce.php? what are the ._* files for?

<img width="1511" alt="screen shot 2018-08-06 at 18 29 55" src="https://user-images.githubusercontent.com/179761/43711913-ea1b15ba-99a6-11e8-86a6-6ea99e8579ba.png">

**Comment by wiiiimm** [comment]
problem went away once I removed all of the ._FILENAME files from within the plugin subfolders... 

```
find ./wp-content/plugins/codepress-admin-columns -type f -name ".*" -delete
```

what are they anyway?

**Comment by wiiiimm** [comment]
turns out the `._FILENAME` files are created in tar on MacOS and that's[ their way of storing file permissions in tar](https://lex-wp-production-zkheoeamzd.now.sh). 

and somehow admin-columns is sensitive to these files (currently the only plugin I have encountered have issues with these files inside their file space)

perhaps there is a way for admin-columns to ignore ._FILENAME files?

PS: Current solution is to use the undocumented flag during tar

```
tar --disable-copyfile -cvzf ...
```

**Comment by DGStefan** [comment]
Thanks for the clarification.
I'll send this ticket to my colleague who wrote the build script.
Maybe it is something we can do on our side, but can you check in the actual download from our website if these files are there? When I download the latest version from our website of from WordPress.org, these files are not there.

**Comment by DGStefan** [comment]
Possible solution:
Adjust Autoloader->get_class_names_from_dir() to handle hidden files
