### ISSUE TITLE
Improve Admin Columns Capability

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1127]
**Issue**
When a specific user once had the 'manage_admin_columns' capability, the capability is actively set for a user (instead of a role). This means that when you use a plugin like members to alter the capability for a role, this will never work for users that have this capability specifically set. 

I believe it is not up to us to set the users capability based on just a check we do. We should at least not set this on user level. We could choose to set the capability for administrator actively but maybe even this is something that should be managed by a third party plugin like Members.

**Comment by JoryHogeveen** [comment]
Totally agree. You could add the capability to the administrator role on installation (or any role based on other capabilities).
