### ISSUE TITLE
Search: Multiselect

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#1140]
For post status, we want a multi-select where multiple statuses can be OR-filtered .

**Comment by JoryHogeveen** [comment]
This would be Pro only right (editable)?

**Comment by JoryHogeveen** [comment]
And, I don't believe WP supports multiple post statuses. Is this for a plugin integration?

**Comment by tobiasschutter** [comment]
Hi Jory, we are working on Smart Filters (codename: Search) which will allow you to use more operators when filtering content. For example, you would be able to filter on date ranges, multiple post statuses, partial strings, and much more.

![image](https://user-images.githubusercontent.com/2736280/46870346-a103d300-ce2e-11e8-9a9a-a0840a0b53be.png)

We are really excited about this new feature, which we are launching anytime now!

I would love some feedback on it. If you are interested, let me know and I'll send you the beta.

**Comment by JoryHogeveen** [comment]
Sure! Send it over :)

But still, WP doesn't support multiple post statuses right? Or is this just for filtering?

**Comment by tobiasschutter** [comment]
Send you a copy on Slack!

**Comment by DGStefan** [comment]
@tobiasschutter 
We decided not to implement the IN operator in the first release.
If we decide to implement this in a future release, you probably want to use Select2 for the IN operator, otherwise people will have to know how to separate values in a  text field, which is not that user friendly.

**Comment by tobiasschutter** [comment]
Hi guys, we got a beta ready and I would love some more feedback on it. We put a lot of time and effort to get it right, and both the ACF and WooCommerce plugins are fully supported... but maybe we missed something that can improve the final release. Any suggestions are welcome. You can get a copy from the [account page](https://www.admincolumns.com/my-account/beta/) or [download it here](https://9gk9th80io3to077nm2z513z-wpengine.netdna-ssl.com/wp-content/uploads/2014/08/admin-columns-pro-4-4beta-5bd166671361d.zip).

Cheers!

**Comment by tobiasschutter** [comment]
Implemented
