### ISSUE TITLE
WYSIWYG editable field for "content" column

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#115]
Introduce editable type: "WYSIWYG". Preferable native WP editor.

**Comment by davidmosterd** [comment]
We got a +1 from a customer and we should check if the WYSIWIG editor might be more easy to use on other places as WordPress itself has introduced the WYSIWIG widget as well in one of the previous releases.

**Comment by tobiasschutter** [comment]
Issue moved: https://github.com/codepress/admin-columns-pro/issues/336
