### ISSUE TITLE
Safari browser has some styling issues with smart filtering

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#1161]
- [ ] Select2 filter has large margins on both sides. You can see this with the Featured Image column.
- [ ] Segment icon is not being shown

![image](https://user-images.githubusercontent.com/2736280/47848294-35c67480-ddce-11e8-92db-99e57b9da215.png)

**Comment by davidmosterd** [comment]
Closing for now, probably cache. Can't reproduce and we also saw this on Chrome, where it was a caching issue.
