### ISSUE TITLE
Refactor Messages a little

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#1169]
Messages cannot be empty, yet it's not a constructor parameter. That gives some issues in tracking the validity of this object.

**Comment by davidmosterd** [comment]
Added fix in Core and Pro, not sure which / if addons also use this.

**Comment by davidmosterd** [comment]
@DGStefan Can you check if there are add-ons / other code that use the internal message classes? Also, we need to test every message whether they are still properly triggered and visible.

**Comment by DGStefan** [comment]
Checklist Triggers Messages
- [x] Review
- [x] Addons available
