### ISSUE TITLE
Core Refactor

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#1177]
- [ ] ListScreen
- [ ] Column
- [x] DataStorage

**Comment by JoryHogeveen** [comment]
Will this impact backwards compatibility?

**Comment by tobiasschutter** [comment]
This will probably not be 100% backward compatible. We want to move forward with the code and get rid of some technical debt. We don't want to make too many concessions on that part. This refactor will open some good new possibilities; such as a composite column, and storing data as JSON or PHP in addition to the DB.

However, I think we'll be able to build in some legacy support for the Column object. It currently doesn't have a constructor and most of its methods can be re-purposed or made deprecated. We will definitely think of our co-developers, and try to make the transition as smooth as possible - without compromising our goal :)
