### ISSUE TITLE
Make it possible to change encoding for Export csv

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1191]
My French client uses Excel 2016 to open the CSV export. Unfortunately the format is not perfect and he must use « import CSV », change delimiter, the encoding, to have a correct display (like https://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0). Also he can use an online conversion tool to Excel (like https://convertio.co/fr/csv-xls/). 

One solution is to change the encoding
classes/Export/classes/Exporter/CSV.php 
after fopen line 26 
add fprintf($fh_memory, chr(0xEF).chr(0xBB).chr(0xBF)); 

more information:
https://stackoverflow.com/questions/21988581/write-utf-8-characters-to-file-with-fputcsv-in-php

**Comment by DGStefan** [comment]
Of course this goes for other languages as well.

**Comment by tobiasschutter** [comment]
Related: https://stackoverflow.com/questions/21988581/write-utf-8-characters-to-file-with-fputcsv-in-php
