### ISSUE TITLE
Global WP_List_Table for Bulk Edit

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#1192]
For some pagination args we rely on the global WP_List_Table of WordPress, Buddypress for example does not. We can work around that, but other new addons might do so as well. It might surface one dat that we need to address this.

**Comment by tobiasschutter** [comment]
Moved: https://github.com/codepress/admin-columns-pro/issues/364

**Comment by lkraav** [comment]
@tobiasschutter is it possible to get an invite to codpress/admin-columns-pro?

**Comment by tobiasschutter** [comment]
@lkraav Hi Leho! Github charges us $4 per month for private repo access per member. Therefor we decided to only add collaborators. I hope you understand.

**Comment by lkraav** [comment]
Add it to my ACP subscription price or send an invoice? Knowing about open issues is worth >>> than $50/year.

**Comment by lkraav** [comment]
Also, didn't GH just become free for all teams a few days ago? https://github.blog/2020-04-14-github-is-now-free-for-teams/

**Comment by tobiasschutter** [comment]
We are on a paid plan and they still charge us for each member. We won't send you an invoice. I have sent you an invite.
