### ISSUE TITLE
Users Page incorrectly add filter menu to the bottom

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#1203]
![image](https://user-images.githubusercontent.com/2736280/51916109-e8fa3600-23dc-11e9-8e45-f50532f06276.png)

**Comment by DGStefan** [comment]
@tobiasschutter 
I'm not able to reproduce this issue.
Can you check if you have a JS error on your environment because I expect that's the case here.

**Comment by DGStefan** [comment]
FIxed
