### ISSUE TITLE
Store last used segment as preference

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1209]

**Comment by tobiasschutter** [comment]
After leaving and returning to the table screen, all filters will be reset. Preferably you want the last used filter segment to persist when you return to the list table.

Either we store the preference within the browsers session. As long as the browser stays open the last used segment will still be applied. Even when other pages are visited in the meanwhile.

Or we store it within the DB as a user preference. Then the filters will persist even when the browser has been closed en re-opened at a later time.

**Comment by tobiasschutter** [comment]
Moved: https://github.com/codepress/admin-columns-pro/issues/361
