### ISSUE TITLE
Author column select2 dropdown shows  all 8K users!

### ISSUE THREAD

**Issue by samjco** [codepress/admin-columns-issues#1229]
How can I filter the dropdown to show only users of certain roles?

**Comment by tobiasschutter** [comment]
I double checked, but our "Author" column only shows 30 users per ajax request. As soon as you scroll down the select2 menu it will fetch the next 30 users. Could you help us reproduce the issue by explaining the exact steps you took?

**Comment by samjco** [comment]
@tobiasschutter. Yes it does show 30 user per request.

But you can imagine that If I didn’t know the user’s correct spelling of their name, i would be searching forever...

So I was just wondering if possible to just filter it down to show just users of certain roles, not all?

**Comment by tobiasschutter** [comment]
You can search users by ID, Login, Nice name, Email, Lastname or Firstname. All the results are then grouped by Role. We think that should be sufficient in finding the right user. 

If you do want to narrow the results further then I would suggest using the WordPress filter: `pre_get_users`.
