### ISSUE TITLE
Create Interface for creating/managing capabilities for Admin Columns Pro

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1241]
The only way to support 'capabilities' is to build an interface to manage this in our plugin.
For now we decided to put this into a separate plugin/addon.
It should only work to hide/show the features in the interface. Alle permission check will stay 'as is'.

**Comment by tobiasschutter** [comment]
This can be achieved by using the "Hide on Screen" settings per list screen.
