### ISSUE TITLE
AdminColumns display of Pods relationship to WP Comment unusable 

### ISSUE THREAD

**Issue by remcokalf** [codepress/admin-columns-issues#1258]
I have the following, slightly exotic, situation:
I have set up a bi-directional relationship field in Pods, between a Custom Post Type (CPT) and WP Comments (single select).

In the WP backend, on the overview page of the CPT, I want to show the related Comment in an AdminColumns column.

When I do that, this column shows the comment in the form of a date+time, pretty unusable. Worse, it does not link to the comment:

![Schermafbeelding 2019-07-17 om 17 58 41](https://user-images.githubusercontent.com/4609920/61392573-68ae8b00-a8bf-11e9-93b5-3034faa23d0c.png)
For any other relationship field to another CPT, in AdminColumns setup, I get the option 'Display', where I can choose a field to show in the column. 
But not with WP Comments.

So I have a feature request for a 'Display' option for a Pods relationship field to WP Comments, so that I can choose, for example, the Comment Author to display. 
Also very helpful would be the option to display it with a link to the comment.

Alternative solution:
In Pods, in the settings for the relationship field, in the tab 'Additional Field options', you can fill in a field at ‘Display Fields in Selection List’. In the case of a related comment, I can fill in @comment_author. 
This works perfect to show the comment author in the relationship field on the edit post screen of the CPT.
However, AdminColums does not take this setting into account.

Thanks for considering adding these options for Pods relationship field to WP Comments.

**Comment by DGStefan** [comment]
@remcokalf 
Thanks for your feedback. This seems like a valid use case, and we already have a setting that can handle Comment display fields. I extended that setting to work with links also and it will be available in the next release of Admin Columns.

For the Pods integration, I made the change the Comments relationship column works with this Display setting. Please send me a message at support@admincolumns.com so I can send you the beta to test it, if you like.

**Comment by remcokalf** [comment]
@DGStefan I tested the beta.
The Display option for comments now works great, thanks. I can show the author, etc. Word/character limit for the comment content is also very nice.

But there is no link option (yet), is that correct? It would be nice to have a link to the comment, like it works for other related custom post types.

![Schermafbeelding 2019-07-19 om 15 26 31](https://user-images.githubusercontent.com/4609920/61539153-2c079e80-aa3b-11e9-87f2-628eb2c0a648.png)
![Schermafbeelding 2019-07-19 om 15 32 29](https://user-images.githubusercontent.com/4609920/61539154-2c079e80-aa3b-11e9-9946-4e45d38e4d48.png)


By the way, does the beta version also automatically update when AC is updated? (Then I can leave it, and do not have to put the original version back.)

**Comment by DGStefan** [comment]
@remcokalf 
The link option will be available when we release a new version of Admin Columns Pro.
I will probably release this feature today.
You should be able to see the update and update the plugin to the latest version once I uploaded the new version.
