### ISSUE TITLE
Javascript error in Media library

### ISSUE THREAD

**Issue by remcokalf** [codepress/admin-columns-issues#1259]
I have a js error in the console, on the Media Library page (the standard grid view):

TypeError: undefined is not an object (evaluating 'AdminColumns.Table.Columns')
line 1553 of table.js

![Schermafbeelding 2019-07-23 om 19 05 05](https://user-images.githubusercontent.com/4609920/61735244-d9ecb300-ad83-11e9-8835-3544e1ecd659.png)
![Schermafbeelding 2019-07-23 om 19 55 18](https://user-images.githubusercontent.com/4609920/61735245-d9ecb300-ad83-11e9-9f9f-c7c376a86d52.png)

The error is only in the grid view, not in the list view (when AC columns are visible).

**Comment by DGStefan** [comment]
@remcokalf 
Thanks for noticing.
Also found this one myself and already have the fix in place for the next release.
