### ISSUE TITLE
Sorting Events Calendar

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#1265]
_Reported via HS #13033:_ 

We have Admin Columns Pro, Admin Columns Pro - ACF, and Admin Columns Pro - Events Calendar installed.

When viewing Venues (in Events Calendar) we have the Venues column set up as Sortable. However, when we click on the title (to sort) it returns no results.

I'm not exactly sure where the conflict is occurring, but I've found that if I edit admin-columns-pro/classes/Search/Query/post.php and change this line:

`$value = $this->add_meta_query( $value, $query->get( 'meta_query' ) );`

to this:

`$value = $this->add_meta_query( $value, [] );`

**Comment by DGStefan** [comment]
I'm in contact with the customer.
I don't think this is an issue on our side.
There probably is a conflict in the meta_query that too specific to show any records.

**Comment by DGStefan** [comment]
Issue seems to be fixed since a latest version of the Events caledar.
Will close this ticket for now
