### ISSUE TITLE
Format numbers

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#1269]
It would be a nice addition to have the option to select the formatting of numeric values. When you have a custom field for mileage you want to see `127,235`, instead of `127235`. But there are exceptions where you do not want to alter the number, such as the year `2019`. It would be wrong to display this as `2,019`.

We can add a display option to the column settings to customize the formatting for numeric values when applicable. And start with the custom field and ACF columns.

**Comment by DGStefan** [comment]
Implemented in Free with Custom Field support
