### ISSUE TITLE
Convert add-ons to modules

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#127]
Change "Add-ons" tab to "Modules" tab. Integrate all modules (ACF, WC, Yoast) in Admin Columns Pro. Activate modules based on available plugins (e.g. activate ACF module if ACF is installed). Don't deactivate a module automatically if the main plugin is deactivated (e.g. if ACF is deactivated but was active before, we shouldn't deactivate ACF). Use these modules as promotion in the free version.

**Comment by DGStefan** [comment]
Admin Column 4.0 is refactored to support new addons instead of using modules

**Comment by engelen** [comment]
YES!
