### ISSUE TITLE
Error: No select2/compat/dropdownCss

### ISSUE THREAD

**Issue by joseluis** [codepress/admin-columns-issues#1285]
Hi, I'm having a problem with Admin Columns, it doesn't show any fields in the custom field dropdown. This is the error in console:

```
Error: No select2/compat/dropdownCss select2.min.js:1:1449
    j select2.min.js:1
    n select2.min.js:1
    g select2.min.js:1
    apply select2.min.js:2
    e select2.min.js:2
    e select2.min.js:2
    select2 select2.min.js:3
    jQuery 2
    select2 select2.min.js:3
    bindEvents custom-field.js:92
    jQuery 3
    getOptions custom-field.js:36
    _emit index.js:160
    emit index.js:26
    getOptions custom-field.js:45
    jQuery 4
```

And, if I save a column showing an unselected custom field (blank)... In that column it shows the content of all fields, for that post type, as a long string...

**Comment by DGStefan** [comment]
Can you have a look which version of select2 is loaded on your environment?
In your console you should be able to see from which location (plugin) the select2 library is loaded

**Comment by joseluis** [comment]
Version 1.15

**Comment by DGStefan** [comment]
That sounds highly unlikely since select2 is already on version 4.
Can you tell me from which plugin the file was loaded?

**Comment by joseluis** [comment]
Oh, sorry I think I copied a URL GET argument instead of the version shown inside the js... It was really version 4.03.

I found out it came from a theme framework plugin, that was not needed at all, that I could disable and the problem is now solved.

Thank you very much for your time.
