### ISSUE TITLE
Drag and drop images for inline edit support

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1286]
It would be AWESOME if, during inline editing of image fields (like Featured Image and ACF image), we could drag a file straight from the OS and drop it onto the field’s pencil/edit icon, having it upload/save the image automatically in one step.

This would bypass multiple tedious steps (clicking on the pencil, opening media library, dragging image into media library, hitting ‘select’ button in media library).

Would be a massive time-saver for when we have to manually populate/swap a large number of individual images.

**Comment by DGStefan** [comment]
https://www.admincolumns.com/forums/topic/feature-request-drag-n-drop-image-fields/

**Comment by tobiasschutter** [comment]
Moved: https://github.com/codepress/admin-columns-pro/issues/354
