### ISSUE TITLE
Better support for serialized data within Custom Fields

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#1301]
Serialized data is displayed by selecting "multiple values" in the column settings. This will `implode` all values and display the key and value combinations. 

We can enhance this further by allowing the user to define which field (key) should be displayed, ignoring all other values. This can be useful when there is a need to only show a single value from within the serialized data.

This could also mean the data can have support for features like inline edit, sorting, and filtering.

**Comment by tobiasschutter** [comment]
Moved: https://github.com/codepress/admin-columns-pro/issues/360

**Comment by ebertucc** [comment]
What is the status on this? I'm currently working on a site that wants inline editing and filtering for serialized data.

**Comment by DGStefan** [comment]
@ebertucc There are no plans to tackle this any time soon.
Our integrations for the most popular custom field plugins do support serialized data, but to support this out-of-the-box for custom field column that have serialized data is more complicated to make it available in the UI as well.

**Comment by ebertucc** [comment]
Understood. I'll try out the ACF integration. Thanks @DGStefan
