### ISSUE TITLE
Error while updating to 5.0.0.

### ISSUE THREAD

**Issue by remcokalf** [codepress/admin-columns-issues#1317]
Today I tried to upgrade from the previous version to 5.0.0.

While waiting for the update, I got the error below. Also see attached screenshot.

I am using WP5.3,  PHP 7.3.12. After the error I reloaded the Plugins page, reload took some time and then the plugin was updated, no more errors. To be sure I have a full update, I downloaded 5.0.0 fresh copy and reinstalled that.

Never seen this, never had any problems updating Admin Colums previous times.

`Update Failed: Uncaught Error: Argument 1 passed to ACP\API\Request\ProductsUpdate::__construct() must be an instance of ACP\Type\License\Key or null, string given, called in /home/xx/public_html/wp-content/plugins/admin-columns-pro/classes/Updates/Updater.php on line 46 in /home/xx/public_html/wp-content/plugins/admin-columns-pro/classes/API/Request/ProductsUpdate.php on line 16__construct()wp-content/plugins/admin-columns-pro/classes/Updates/Updater.php:46check_update()wp-includes/class-wp-hook.php:290apply_filters()wp-includes/plugin.php:206apply_filters()wp-includes/option.php:1829set_site_transient()wp-includes/update.php:334wp_update_plugins()wp-includes/class-wp-hook.php:286apply_filters()wp-includes/class-wp-hook.php:312do_action()wp-includes/plugin.php:478do_action()wp-admin/includes/class-plugin-upgrader.php:316bulk_upgrade()wp-admin/includes/ajax-actions.php:4421wp_ajax_update_plugin()wp-includes/class-wp-hook.php:288apply_filters()wp-includes/class-wp-hook.php:312do_action()wp-includes/plugin.php:478do_action()wp-admin/admin-ajax.php:175
`

![Schermafdruk 2020-02-10 15 59 39](https://user-images.githubusercontent.com/4609920/74163164-43e68000-4c22-11ea-8998-00ec6f08d0a8.png)

**Comment by DGStefan** [comment]
@remcokalf 
Have a look at this on our forums
https://www.admincolumns.com/forums/topic/error-message/

When we debug the code, this should not happening in the new codebase. The old file that was calling this method, it was indeed a string, but in the new file it is not. Clearing the server cache or re-installing the plugin should fix the issue.

**Comment by remcokalf** [comment]
Thanks. Yes, I reinstalled the plugin, and no more problems so for me it is fixed. 
The only server cache I am aware of is opcache which on on my server. Not sure if that could cause this. I haven't seen any errors during plugin updates for a long time, with many plugins.
