### ISSUE TITLE
Improved segments

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#1327]
Right now segments are integrated with search. While that works good, it does not represent how the LS is rendered when the URL is rebuild as it does not take default / other custom filters into account.

**Comment by davidmosterd** [comment]
Proposal how new segments could work. Supports order, orderby and non
AC filters and combines them as url_parameters along with the segment.

**Comment by davidmosterd** [comment]
@DGStefan please have a look what you think in working, but especially how the JS is written.

**Comment by davidmosterd** [comment]
What this solution does not (yet) accommodate is array-filters e.g. name[]=1&name[]=2, but this is a start.

**Comment by tobiasschutter** [comment]
Can we incorporate these issues as well:
Sharing Segments: https://github.com/codepress/admin-columns-pro/issues/358
Ordering Segments: https://github.com/codepress/admin-columns-pro/issues/356
Load Last Visited: https://github.com/codepress/admin-columns-pro/issues/361

**Comment by tobiasschutter** [comment]
@DGStefan Filters that are using a text input (such as the ranged filters) are not being loaded correctly. You can reproduce it by adding the `ID` column and setting its filter to ranged.

**Comment by DGStefan** [comment]
Done in 5.3
