### ISSUE TITLE
WooCommerce addon: Product Type column

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#135]
Should display if the product is downloadable. Not working correctly. See the native "type" column of WC products.

**Comment by engelen** [comment]
I disagree. The product type column is intended to show only the product type; the native "Type" column from WooCommerce displays all other product type information as well. However, we might do well to add checkboxes for displaying whether a product is downloadable or virtual. A potential problem with this is that many add-ons add additional properties of the same sorts as "downloadable" and "virtual": (how) should we treat those?

**Comment by tobiasschutter** [comment]
I agree. There is also a work around avaialble by using a Custom Field column to display and edit the "Downloadble" and "Virtual" options. Closing this issue.
