### ISSUE TITLE
Addon: Add columns to the search on the listings screen

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#140]
Make the columns searchable through the listings search.
![enable_search](https://cloud.githubusercontent.com/assets/2736280/6460224/a088ddde-c195-11e4-9428-0d3c98b692fb.png)

**Comment by tobiasschutter** [comment]
See branch 'custom-search'.

It's partially working for custom Fields. 

Next (sorted by priority):
- All custom field types
- ACF fields
- All other columns that can benefit from search ( such as Parent, Roles, Shortcodes..)
- WooCommerce columns

**Comment by renestalder** [comment]
Any news about this?

**Comment by rayredberry** [comment]
Is there anything new about this ?

**Comment by davidmosterd** [comment]
There is an update here: https://www.admincolumns.com/blog/current-status-development/ Summary: we are working on this; but we had to get some structural issues out of the way first. This is going well and we expect to work on search and two add-ons soon after.

**Comment by urbanecos** [comment]
Just checking to see if there is any news on this? Appreciate all your work!

**Comment by dleeward** [comment]
Found this post: https://wordpress.stackexchange.com/questions/16637/how-to-filter-post-listing-in-wp-dashboard-posts-listing-using-a-custom-field/16641#16641  Would it interfere with the Admin Columns plugin?

**Comment by DGStefan** [comment]
We have planned a new Search feature for Admin Columns Pro somewhere Q3 2018. It will probably not work with the default Search box but it will probably look more like an extended filter feature. This ticket will be closed and a new ticket related to the upcoming feature will be opened as soon as we start development.

**Comment by jan1980** [comment]
Dear friends, is this still under consideration? Many thanks,
