### ISSUE TITLE
Pods: Support for Multiple Custom Field data with identical keys

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#143]
http://wordpress.org/support/topic/custom-field-with-multiple-values-only-showing-one-field-type-multiple-values?replies=3

**Comment by mvasin** [comment]
I'm very interested to have this fixed, to be able to display Pods relationship fields with multiple values.

**Comment by tobiasschutter** [comment]
This has been fixed in the Pods add-on
