### ISSUE TITLE
Column "Display Author As" make display value clickable

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#148]
Is there any way to make the “Display Author As” column results clickable to view all of that author’s posts in the same way the standard “Author” column does?

by Justin

**Comment by engelen** [comment]
I've implemented a "Link To" field for this column, allowing you to choose where the author name links to (options: no link, edit author, author posts, public author page on website).

https://github.com/codepress/codepress-admin-columns/tree/extended-author-column
