### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#151]
`PHP Fatal error: Unsupported operand types in /wp-content/plugins/admin-columns-pro/classes/inline-edit/classes/model.php on line 629`

Operator '+' gives a fatal:

`$editable['options'] = $option_null + $editable['options'];`

source: https://www.admincolumns.com/forums/topic/fatal-error-inline-editmodel-php/

**Comment by engelen** [comment]
Fixed https://github.com/codepress/admin-columns-pro/commit/ffc6bc56f356a18f045af36c98ab15b7b4a12667.
