### ISSUE TITLE
WooCommerce column: attributes for variations

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#159]

**Comment by tobiasschutter** [comment]
Product Variations uses the defined attributes.
A variation can have multiple attributes assiged, but only one item from each attribute.
For example a single variation could look like: Red (color attribute), M (size attribute).

A column could be a variation picker, where you select a attribute (color). And the column would list all used colors for that particular attribute (color).

**Comment by tobiasschutter** [comment]
Implemented!
