### ISSUE TITLE
Renewal notice in plugin

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#160]

**Comment by engelen** [comment]
Initial implementation completed (https://github.com/codepress/admin-columns-pro/tree/renewal-notice). The notice is shown in the plugin list, on all admin screens until the close-link is clicked and always in the Admin Columns settings page.

@tobiasschutter: A few methods are still needed inside the license manager and API:

`get_licence_status()`
Currently returns true (valid key) or false (no valid key). Should return "valid", "invalid" or "expired".

`get_license_expiry_date()`
Get expiry date (UNIX timestamp) for license expiry date.

`get_renewal_threshold_period()`
Get time (in seconds) before actual expiration of an activation key by which the notification should appear. Example: 60 \* 60 \* 24 \* 10 to start displaying the upgrade notice 10 days before the license will expire.

`get_license_renewal_discount()`
Get available renewal discount for license.

**Comment by engelen** [comment]
Todo: "check license" button in notice.

**Comment by tobiasschutter** [comment]
Done!
