### ISSUE TITLE
Only display editable icon on hover

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#174]
Currently when you have the inline-edit "on", all icons will be visible. Maybe it would be better if the icons stay hidden untill you hove the actual column value. (feedback please)

To have a look at the result, use this code:

```
function my_only_display_editable_actions_on_hover() { ?>
    <style type="text/css">
        .cacie-editable-container .cacie-cell-actions { display: none !important; }
        .cacie-editable-container:hover .cacie-cell-actions { display: block !important; }
    </style> <?php
}
add_action( 'cac/admin_head', 'my_only_display_editable_actions_on_hover' );
```

**Comment by engelen** [comment]
We've considered and implemented this approach when we first started developing inline editing. Even though it does affect the list table less and ensures a better overview, it's quite difficult to see which columns are editable. A solution to this would be to add an icon or another type of mark in the column header, showing that the column is editable. However, there are two problems with this. Firstly, without fixed table headers, scrolling down on longer lists makes the column headers invisible, and thus hides the information about editability. Secondly, there are columns for which not all items are editable. For example, an entire post may not be editable based on permissions, and certain types of WooCommerce columns also have editability checks per post.

All-in-all, I believe our current approach is quite solid.
