### ISSUE TITLE
Use grunt to create the pot file and push/pull from Transifex

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#176]
Transifex and Grunt: http://wp-translations.org/grunt-transifex-wordpress/
Grunt package: https://www.npmjs.com/package/grunt-wp-i18n
WP Doc i18n: https://codex.wordpress.org/I18n_for_WordPress_Developers

**Comment by DGStefan** [comment]
Solution already made with gulp and bashcommand
