### ISSUE TITLE
Add network option for license key in multisite

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#178]

**Comment by tobiasschutter** [comment]
Add message to license key on multisite telling that the key is valid for the entire network.

**Comment by davidmosterd** [comment]
Maybe this needs a new ticket, but I propos we add a settings screen to the multi-site install where you can enable your license. There we can explain that once a licence is set here, it will apply to all licenses and that the current settings screen in a site will be removed/ contain a message about this screen. When left blank, each install can manage it's own install.

I think this is not that hard to do and a good alternative for situations where you do not want multiple installs to have an effect on each others license state.

**Comment by davidmosterd** [comment]
I have submitted a patch containing a possible solution.

Branche: issue-178-*
