### ISSUE TITLE
Move columns between storage models

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#180]
We could offer a method to copy columns to other storage models, or move them to other storage models. What would be a good way to implement this? We could offer a drag-and-drop-option, or we could feature a menu arrow with a list of advanced operations. @tobiasschutter, what do you think?

**Comment by tobiasschutter** [comment]
There is a work around in which you can accomplish this already, but it's not very user friendly. You can export to a json file and change the first json key to another storage model. For example you can change "post" to "page" and re-import the json file. 

If we want a better UX I would suggest an advanced tab with a dropdown menu to clone from/to another storage model. This cloning process should also filter out al the non supported columns for that particular storage model.

**Comment by Tyree** [comment]
In addition to copying an entire column set, if you could extend the functionality of the clone feature for a particular column to be able to not only duplicate it within the current post type, but also to another post type, that would be excellent.

**Comment by tobiasschutter** [comment]
This would add too much complexity to the UI, and the use cases are too limited. Therefor we rejected this feature.
