### ISSUE TITLE
UI change for Custom Fields

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#182]
The current column settings design does not suffice for the amount of options we support with our more complex columns. I believe we might need some separation of settings, in one way or another. I've drafted a small concept to support the idea.

https://www.evernote.com/shard/s321/sh/1ff87272-9ffc-498a-82f2-2df0485312e9/8d14b7c8ed19182d6f1292155dfffdb1/deep/0/Admin-Columns-Settings---CodePress-Admin-Columns---WordPress.png

@tobiasschutter, do you agree that our column settings have become too complex for the current settings layout?

**Comment by tobiasschutter** [comment]
I agree, especially for CF now where you have coditional settings like the inline-editing boolean values. This will also be usefull for more conditional statements that we might implement in the future.

The added text "enable sorting" etc. seems obsolete as it's also in the label. 

The boolean values will probably need it's own tooltip with a clear explanation.

![ac_custom_fields](https://cloud.githubusercontent.com/assets/2736280/7133203/157e43a6-e291-11e4-873d-7fd56bd2a097.png)
