### ISSUE TITLE
WooCommerce add-on: add notice when version is not supported

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#184]
Currently inline edit does not work on WooCommerce 2.0.20. Either we support this version or display a notice.

**Comment by engelen** [comment]
Do you have an overview of versions of WooCommerce we do and don't support? Or maybe the oldest version of WooCommerce we support? I've implemented the functionality, we just need the version number.

**Comment by DGStefan** [comment]
Won't fix
