### ISSUE TITLE
Media column: Metadata

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#194]
Add a column for attachment metadata. 

Additional metadata for an attachement is stored serialized in "_wp_attachment_metadata". Add column to select the metadata field. This should field select should be cached as we need to retrieve all metadata and unserialize it.

**Comment by DGStefan** [comment]
@tobiasschutter 
We have an EXIF column, this contains all information that is available in the metadata field.
Do you have other fields in mind?
