### ISSUE TITLE
Column option to remove category dropdown from post listings screen

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#206]
Category filter is always visible. We should be able to make a column option which can enable/disable the default category filter dropdown.

**Comment by engelen** [comment]
I don't believe this is possible. The restriction dropdowns (filters) are not filterable but added through the action `restrict_manage_posts`. @tobiasschutter did you have a workaround in mind when you created this issue? If you didn't, please close it as wontfix.
