### ISSUE TITLE
Conditionals for displaying columns

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#209]
Conditional columns would allow you to toggle column visibility based on, for example, user details. A use case of this would be to disable column visibility for certain user roles, allowing you to show different columns depending on the users level of access.

**Comment by DGStefan** [comment]
@engelen 
I believe this can be managed by using column sets properly.
You can make different columns sets for specific roles instead of giving columns this behavior. what do you think?

**Comment by engelen** [comment]
Agreed, this is exactly the behaviour that was implemented in the column sets release.
