### ISSUE TITLE
WooCommerce improved filtering support

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#214]
Improve filtering support for WC columns - Order, Products and Coupons.

Such as Order Status, Type, Code, Featured, Product Type, Reviews Enabled etc.

**Comment by engelen** [comment]
Implemented:
Sort by: Customer message, order status, payment method
Filter by: Customer message, order status, payment method, reviews enabled

**Comment by tobiasschutter** [comment]
Option "No" doesn't work.

**Comment by DGStefan** [comment]
Option "No" not part of this ticket.
Filtering for fields above is tested and ready for deployment
