### ISSUE TITLE
Add new Posts from listing screen

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#22]
We want to add rows to the all-posts admin view from that page, without leaving the page. An AJAX approach or the fashion employed in the dashboard's "Quickpost" widget is ideal.

"Add new" posts from listing screen.

**Comment by engelen** [comment]
Should possibly be moved to 3.6; examine possibilities for 3.5.

**Comment by tobiasschutter** [comment]
This should be a seperate plugin or add-on.

**Comment by tobiasschutter** [comment]
duplicate: https://github.com/codepress/admin-columns-issues/issues/354
