### ISSUE TITLE
WooCommerce Subscriptions add-on

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#223]
Support for WooCommerce Subscriptions columns. 

This will need an added storage model that loads WC_Subscriptions_List_Table, which is an extension of WP_List_Table.

Columns
- Variations (used custom variation column and added subscription support)

http://www.woothemes.com/products/woocommerce-subscriptions/

**Comment by DGStefan** [comment]
@tobiasschutter 
I have a copy of WooCommerce Subscriptions. Are you talking about[ this plugin?](https://www.woothemes.com/products/woocommerce-subscriptions/)

I don't think we need a new storage_modal because all subscriptions are loaded in the same overview as default products.

**Comment by ericgreenspan** [comment]
This would be amazing gents! I wish I knew how to help.

**Comment by DGStefan** [comment]
This will be part of the WooCommerce integration issue and will be removed from this list
