### ISSUE TITLE
ACF add-on filtering bug 

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#224]
I'm having an issue with the advanced custom fields addon. I select a field and it capitalizes the label and thus breaks the filter.

e.g. orderby=EndDate&order=asc

If i changed 'EndDate' to just 'enddate' than it works fine.

**Comment by DGStefan** [comment]
I'm trying to reproduce this issue.
The sorting key is managed by using sanitation of the label. It seems that an other plugin is interfering with our sorting logic.  

On way to solve this is to lowercase all sorting keys. 
@tobiasschutter what do you think?

**Comment by tobiasschutter** [comment]
Solved
