### ISSUE TITLE
add max-width to featured image column

### ISSUE THREAD

**Issue by nicmare** [codepress/admin-columns-issues#227]
you should add max-width:100%;height:auto to image of featured image column: https://www.dropbox.com/s/emgo7780urzclup/Screenshot%202015-07-09%2015.34.04.png?dl=0
![screenshot 2015-07-09 15 34 04](https://cloud.githubusercontent.com/assets/898582/8596509/220ebb66-2650-11e5-859f-3c11fa9e1ee6.png)
so it can scale down with column size (which is 5%)

**Comment by tobiasschutter** [comment]
We already use the max-width property, but it's controlled by the columns settings. You could can set your own max-with by chosing a width in the columns settings.
