### ISSUE TITLE
ACF addon: Linktarget field seems not to work, sometimes

### ISSUE THREAD

**Issue by nicmare** [codepress/admin-columns-issues#228]
thats my acf field: https://www.dropbox.com/s/k56pmfmbpt66b3j/Screenshot%202015-07-09%2015.41.52.png?dl=0

here you see it in action: https://www.dropbox.com/s/uln225o7vcpiqe9/Screenshot%202015-07-09%2015.42.10.png?dl=0

same post in the cpt table (green image) but there is no value displayed:
https://www.dropbox.com/s/biow2yhg7aoey5w/Screenshot%202015-07-09%2015.42.42.png?dl=0

but in the first row it shows the right value. and for some reason you require to enter at least one character. but in acf this is not neccessary when using a field from type "link".

this is what you require:
https://www.dropbox.com/s/43mw01z2vhnx1fk/Screenshot%202015-07-09%2015.44.30.png?dl=0

this is what it should do instead:
https://www.dropbox.com/s/wjzgg52cwqpfzrs/Screenshot%202015-07-09%2015.44.50.png?dl=0

a nice list of posts sorted by CPTs

**Comment by tobiasschutter** [comment]
Thank for reporting this issue nic. We'll be looking into it!
