### ISSUE TITLE
ACF Addon: let gallery items float

### ISSUE THREAD

**Issue by nicmare** [codepress/admin-columns-issues#229]
![screenshot 2015-07-09 15 55 53](https://cloud.githubusercontent.com/assets/898582/8597008/0f67b186-2653-11e5-9258-e8c8f8601be1.png)
i am using the acf field from type "gallery". as you can see your plugin put one item in each line. please let them float or limit the number of items here

**Comment by tobiasschutter** [comment]
Added to the roadmap. Thanks for submitting the issue!

**Comment by DGStefan** [comment]
@tobiasschutter 
Fix made and ready for merge 
branche: floating-gallery
