### ISSUE TITLE
Repeater Field and The Flexible Content Field add-ons can give an error in ACF version 4 

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#242]
This was reported on the forum: https://www.admincolumns.com/forums/topic/fatal-error-using-acf-date-picker/

The function acf_get_value() is called but not supported in ACF version 4 in combination with the repeater field or the flexible content field. 

We are currently looking into finding the best replacement that works for V4 and V5 (ACF PRO).

**Comment by davidmosterd** [comment]
acf_get_value seems to be deducted from acf_field_functions::load_value in V4. I will investigate a wrapper function that takes V4 and V5 in consideration.

**Comment by davidmosterd** [comment]
I have proposed a fix in a pull request; the idea is to fall back to the get_field_object method when acf_get_values() is not available. This way it should only impact ACF4 users in a positive way and have no effect on ACF5 (pro) users

**Comment by DGStefan** [comment]
Already fixed
