### ISSUE TITLE
WPML issue 3.4.2

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#243]
The flag column is showing the same flags for all languages.

https://www.admincolumns.com/forums/topic/admin-columns-and-wpml/

**Comment by DGStefan** [comment]
See forum topic on how to reproduce this.
Can't think of a suitable solution to fix this.
- Column must be disabled when posttype is not translatable
- Column can be disabled when posttype is translatable

**Comment by tobiasschutter** [comment]
Fixed
