### ISSUE TITLE
WooCommerce Parent column

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#247]
The WooCommerce Parent column should be able to display
- ID (links to edit post)
- Title (links to edit post)
- Author (links to edit author)

The output format can be selected from the column settings.
CPAC_Column::display_field_post_property_display() is available to create the dropdown.

It should also be:
- Editable
- Sortable
- Filterable

( A child product can have a parent bys electing a grouped product from "Linked Products > Grouping". )

**Comment by DGStefan** [comment]
Ready for merge
Branche: woo-parent-columns-sorting-editing (ACP Pro)
Branche: parent-product (Woocommerce addon)

**Comment by tobiasschutter** [comment]
Default value should be Title

**Comment by tobiasschutter** [comment]
Merged
