### ISSUE TITLE
Filter ranges for custom fields

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#248]
Currently, only filtering on current matches is possible. 
It should be possible to filter on ranges.
This can be accomplished by adding filter compare option in the column menu, such as:
- Exact match
- Larger than
- Smaller than

**Comment by tobiasschutter** [comment]
Created a branch where ranges has been implemented for Custom Field type Numeric.
codepress/admin-columns-pro@95b33abbf2c703bf45b5dfb4dbeb5f2b6226f4db

Next would be ACF or date ranges for CF.

Let's try to and push this for v3.6

**Comment by tobiasschutter** [comment]
Done
