### ISSUE TITLE
Ability to select multiple values for each filter

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#25]
Ability to select multiple values for each filter. So if you have a filter with options "Blue", "Green", "Red" be able to filter by "Blue" and "Red" at once.

submitted by Tai

**Comment by tobiasschutter** [comment]
A temporary workaround for this would be to add multiple columns of the same type.

**Comment by DGStefan** [comment]
This will be solved by the new Search feature planned for 2018.
I will close this topic since this is already on our roadmap
