### ISSUE TITLE
Make sure all instances point to the correct site url

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#252]
The code contains a few references to http://admincolumns.com. These should be rewritten to https://. Also I think there should be a constant or method that gets this url so there are no references at all. Subpages can be handled like

`acp_site_url() . '/path/?parameter=value` or maybe use the query functions of WP this and use it like `acp_site_url( '/path/?parameter=value' )` or something like that.

**Comment by tobiasschutter** [comment]
Pull requests merged:
https://github.com/codepress/codepress-admin-columns/pull/74
https://github.com/codepress/admin-columns-pro/pull/35

**Comment by davidmosterd** [comment]
Can be merged, all instances are replaced with the new ac(_get)_site_url() or adjusted to correct url when it's a comments or textual reference.
