### ISSUE TITLE
Add support for composer

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#253]
Based on https://roots.io/wordpress-plugins-with-composer/ we have had requests to support composer. This allows installs who manage their plugin by composer to more easily manage our plugin  instead of making an exact reference and update it manually.

**Comment by DGStefan** [comment]
@davidmosterd 
Another example on how ACF has done it.
https://github.com/PhilippBaschke/acf-pro-installer

**Comment by DGStefan** [comment]
Related issue:
https://discourse.roots.io/t/admincolumnspro-with-composer-zip-extracted-improperly/3413/4

**Comment by tazeverywhere** [comment]
Hello,
work fine for me in `wordpress-plugin` folder, but not in `muplugins`.
I think the license key is missing in auto-activation process, but don't know how to specifiy it, for exemple in the `.env` file.
Any idea ?

my composer setting
```
{
            "type": "package",
            "package": {
                "name": "codepress/admin-columns-pro",
                "version": "4.1",
                "type": "wordpress-plugin",
                "dist": {
                    "type": "zip",
                    "url": "https://www.admincolumns.com/?wc-api=software-licence-api&request=plugindownload&licence_key=xxx&plugin_name=admin-columns-pro"
                },
                "require" : {
                    "composer/installers": "^1.0"
                }
            }
        }
```

all the best.

**Comment by timportner-pp** [comment]
Bit late, but:

.env file:
`ACP_LICENCE=""`

wp-config.php:
`define('ACP_LICENCE', getenv('ACP_LICENCE'));`

**Comment by tazeverywhere** [comment]
Nice @timportner-pp , will check that, thx.

**Comment by adamtomat** [comment]
Thoughts on using a technique like this?

https://deliciousbrains.com/composer-premium-wordpress-plugins/

**Comment by DGStefan** [comment]
This topic is closed.
Composer support is added and all necessary information can be found on the account page on our website

**Comment by tobiasschutter** [comment]
Just for reference, here is the documentation page on how to install Admin Columns thought composer: https://docs.admincolumns.com/article/95-installing-via-composer
