### ISSUE TITLE
Error with WP Email Template LITE & BBPress activated

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#255]
Fatal error: Call to undefined method stdClass::in_admin() in /wp-includes/load.php on line 644

Admin Columns & WP Email Template LITE = Okay
Admin Columns & BBPress = Okay
Admin Columns & WP Email Template LITE & BBPress = Error.

**Comment by DGStefan** [comment]
traceback turns out this is not because of our plugin.
filter array is probably overwritten of changed somewhere in one of the two plugins.

To look any further:
storage_model/post.php
$columns = (array) apply_filters( 'manage_edit-' . $this->key . '_columns', array() );
