### ISSUE TITLE
Textdomain change to 'codepress-admin-columns'

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#256]
From wp.org:

For your plugin to be imported properly, the text domain must match the slug:
​\* Admin Columns : codepress-admin-columns
A scan of the code indicates the following issue with your plugin:
- Admin Columns : Text domain mismatch. The text domain 'cpac' listed in the plugin header must match the plugin's slug, codepress-admin-columns.

Please update your plugin before next week to fix the issue listed above.

**Comment by DGStefan** [comment]
Textdomain changed for both plugins
