### ISSUE TITLE
Show Role value besides Role name

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#260]
Currently when you can only show the role name but not the actual role value in columns.

To clarify: When I use a plugin such as the “Members” plugin with which you can manage custom user roles, it differentiates between “Role name” and “Role”. The latter is what I’d like to see next to the Role name as this can vary .

https://www.admincolumns.com/forums/topic/role-value-not-name/

**Comment by tobiasschutter** [comment]
We could add "Role key" within a tooltip.

**Comment by DGStefan** [comment]
Created a new columns calles 'Roles'. This columns support to show more than 1 role and also adds filtering, sorting and inline-edit support

**Comment by DGStefan** [comment]
Can be tested in branche /new-user-role
