### ISSUE TITLE
can't filter media by author

### ISSUE THREAD

**Issue by nicmare** [codepress/admin-columns-issues#267]
when i activate author filter for media, i get following error in media library:
Fatal error: Call to undefined method CAC_Filtering_Model_Media::get_values_by_post_field() in /www/htdocs/w00885cf/top10pranks/wp-content/plugins/admin-columns-pro/classes/filtering/classes/media.php on line 208
WP  Version 4.3.1
ACP Version 3.5.2
ACP ACF add-on Version 1.3
Advanced Custom Fields Pro Version 5.3.1

**Comment by tobiasschutter** [comment]
This has been fixed with the latest release 3.6 (released 13th October)
