### ISSUE TITLE
Feature Request: Stack multiple fields in a single column

### ISSUE THREAD

**Issue by dleeward** [codepress/admin-columns-issues#273]
Stacking multiple fields in a single column would help to keep screen widths narrower, especially when showing posts with excerpts that may be many lines high.

**Comment by tobiasschutter** [comment]
It is an interesting concept. Almost like a grouped column, which let's you merge multiple columns. However, it would also add a level of complexity which we do not necessarily want. This issue could need some additional thought.

**Comment by dleeward** [comment]
If displaying multiple fields in the same column is too complex, maybe allowing multiple fields to be concatenated first (with a choice of separators like comma or LF) and then displayed as one string?

**Comment by DGStefan** [comment]
Rejected because of complexity for GUI.
Can be solved by creating an own custom column
