### ISSUE TITLE
Filtering options with select2 and ajax

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#294]
1. Some filter menu's can get very large (over 2000 records) which leads to performance issue in the browser. The DOM can't process that many elements in a select field properly. 

The solution would be to have a SELECT2 dropdown which will be populated with ajax.

The standard select menu should be automaticly converted to select2 when the total items count get over 200.

2. Search filter option. A search box at the top of each filter so when a filter has many, possibly hundreds / thousands of values, you can search the filter options for the value you are looking for.

**Comment by DGStefan** [comment]
Pull request for testing:
https://github.com/codepress/admin-columns-pro/pull/50

**Comment by LukeAbell** [comment]
Would love to help test this.

**Comment by Garconis** [comment]
Any update on this? Really looking forward to it.

**Comment by Garconis** [comment]
This must be related to this issue? https://www.admincolumns.com/forums/topic/very-laggy-functionality-with-custom-fields/

**Comment by DGStefan** [comment]
This will be completely rewritten in our upcoming search feature which is planned for 2018
