### ISSUE TITLE
Add support for export current overview to Excel/CSV

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#296]
Can this be an addition to our plugin or is this to far from our focus?

**Comment by tobiasschutter** [comment]
This should be an add-on.

**Comment by Garconis** [comment]
Very much looking forward to this. Currently have to use a Chrome extension to capture the table/view. https://chrome.google.com/webstore/detail/table-capture/iebpjdmgckacbodjpijphcplhebcmeop

But then I have to manually make sure the amount of entries shown is all of them. Would be great to just have a CSV export option that outputs all the columns of the current filtered/sorted view... even if those entries/rows are on subsequent pages.

**Comment by Garconis** [comment]
Any update on this? Would love to start trying it out... even if the add-on is in alpha/beta still.

**Comment by tobiasschutter** [comment]
Finally! I can close this ticket :P It's in our latest release: https://www.admincolumns.com/export-content-csv/
