### ISSUE TITLE
Optimise ACF sorting on single values

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#299]
When ACF stores simple values like number or date, we could optimise performance by using the native WP_Query over sorting with PHP.

**Comment by davidmosterd** [comment]
I would like to hear what you guys think of the submitted patch for this.

**Comment by tobiasschutter** [comment]
This branch is very similar to the merged one, which one is correct?

https://github.com/codepress/admin-columns-pro/commits/%23299-acf-sorting-single-value-callback
