### ISSUE TITLE
Support to show empty and not empty options in filter dropdown

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#301]

**Comment by mircoh** [comment]
Thank you for creating this issue.

It would be great to **only** show the options empty/not empty. Thank you!

**Comment by DGStefan** [comment]
In Admin Columns 4.0 almost every column has the empty/not empty options in the dropdown.
If it is not you can even use this filter

add_filter( 'cac/addon/filtering/dropdown_empty_option', '__return_true' );
