### ISSUE TITLE
Option to show only first image on Custom field: Image / Media Library

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#311]
in my theme i have a custom field called attachment, in this field is present more then 1 image (average 10-15 images), now when i setup this custom file in a custom column i see every image for every custom post (so this is very slow site)

so, i want show only the first image of this images, can you tell me if this it's possible with your plugin, and if yes , how ?

**Comment by tobiasschutter** [comment]
Implemented in 4.0.8
