### ISSUE TITLE
Show newlines on content field

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#312]
The content field sometimes contains simple content (e.g. a log or todolist). For these kind of simple content fields it might be helpful to show at least the newlines "\n".

But the "Text" display or even the "WYSIWYG" might even apply.

We could add a simple checkbox "show newlines" or "format display" that enables this.

**Comment by DGStefan** [comment]
We already have quite some formatting settings for this field, and such a new setting would probably interfere with these other settings. Besides that, those other formatters already do what you suggest. It can always be altered by using a hook.
