### ISSUE TITLE
Ranged date filtering for more content types

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#323]
Ranged date filtering:
- [x] Post publish date (Since 4.0)
- [x] Comment publish date
- [x] User register date

**Comment by davidmosterd** [comment]
Certain dates have a native filter in WP like post published date. We have to work around/ with that in a elegant matter: to extend, replace or have them side by side.

First steps will be to make them ACP filterable, then make them support ranges as well.
