### ISSUE TITLE
ACF Filtering for Users

### ISSUE THREAD

**Issue by findingsimple** [codepress/admin-columns-issues#330]
I can see both https://github.com/codepress/admin-columns-issues/issues/328 and https://github.com/codepress/admin-columns-issues/issues/327 have been fixed.

I've upgraded to 3.7.1 (and previously 3.7.0) but I still can't see any of the filters I have setup for Users

e.g. http://cl.ly/1B2d113p2N0C and viewing the users screen there is no Category filter (but the column is there). Was working prior to 3.7.x

I'm using multi-site - and its not working on either the network or site users screens.

**Comment by findingsimple** [comment]
https://github.com/codepress/admin-columns-issues/issues/336

**Comment by tobiasschutter** [comment]
We'll try and fix this one for 3.7.3, thanks for reporting.

**Comment by tobiasschutter** [comment]
Fixed with https://github.com/codepress/codepress-admin-columns/commit/a1fbd25db0ce31a5a233cbfdf32483db874d6cf2
