### ISSUE TITLE
Change datepicker for datetimepicker to support times in date fields

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#331]
This would require some refactoring for inline edit and filtering because these are two different date pickers. Best solution is to choose a date/time picker that can be used for both inline edit and filtering.

**Comment by davidmosterd** [comment]
To elaborate on the requirements:

- Date + Time (best would be context: time relevant or not)
- Should show custom new display format
- Should take in consideration the required format for storing the date for default WP columns.

**Comment by DGStefan** [comment]
Duplicated and closed in 4.0.10
