### ISSUE TITLE
Add column can load wrong columns options

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#347]
1. Enable ACF addon
2. Click add column

You will now see a ACF column with checkbox field. This column should have inline edit available, but doesn't. Column should be re-init after JS added it to the DOM.

**Comment by DGStefan** [comment]
@tobiasschutter 
Why not just refresh the complete column after adding it to the dom?
All other events are available in the refresh method and you're always sure that you the correct settings.

**Comment by DGStefan** [comment]
:exclamation: This is created in a branche from #56
