### ISSUE TITLE
Adding a button to add a post inline

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#354]
Reference:
https://www.admincolumns.com/forums/topic/adding-a-button-to-add-a-element-inline/

Create the possibility to inline create a new post in the overview.
Make a decision if we add this feature in the core or in a separate addon/plugin.

**Comment by tobiasschutter** [comment]
This should be a separate plugin or add-on. It does not fit the scope of Admin Columns.

**Comment by tobiasschutter** [comment]
I created a working concept for this: https://github.com/codepress/ac-addon-add-new-inline
