### ISSUE TITLE
Comment heading appears on not supported post types

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#377]
Reproduce:
1. Add code snippet 
2. Remove comment column on settings screen & save
3. Refresh column settings again.

Comments heading re-eappers.

```
function sw_remove_support() {
    remove_post_type_support( 'post', 'comments' );
}
add_action( 'admin_init', 'sw_remove_support', 15 );
```

**Comment by DGStefan** [comment]
related to https://github.com/codepress/admin-columns-issues/issues/381

**Comment by DGStefan** [comment]
Tested in dev with latest merge and fixed
