### ISSUE TITLE
Default columns from other plugin are not recognized in ACP setting page

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#379]
List of plugins with known issues:

:white_check_mark: Custom Bulk/Quick Edit
:white_check_mark: Yoast (without our own fix)
WooCommerce Cost of goods plugin (not tested)
Events Manager (not tested)

:white_check_mark: Content Progress (columns are available in list, but are removed when the columns are saved) [ticket](https://wordpress.org/support/topic/conflict-with-content-progress-plugin?replies=1)

**Comment by adam-jones-net** [comment]
To clarify, specifically with Custom Bulk/Quick Edit there is an issue that in list pages of posts the tick boxes for bulk actions in the far left column disappear so bulk actions such as delete become unusable.     This WAS working in earlier versions of Admin Columns plugin and my recent upgrade to 3.7.1 broke this.

**Comment by DGStefan** [comment]
Test with Custom Bulk/Quick Edit:
:white_check_mark: Columns are added and recognized in overview
:white_check_mark: Checkbox column is not rendered correctly -> Have to use filter:

function add_cb_to_overview ( $columns ){
    $columns['cb'] = '<input type="checkbox" />';
    return $columns;
}
add_filter( 'manage_post_posts_columns', 'add_cb_to_overview', 1 );

**Comment by adam-jones-net** [comment]
Hi @DGStefan , can you clarify about this add_cb_to_overview () and what needs doing?  I've added but still no checkboxes on my install with Custom Bulk/quick edit.

**Comment by DGStefan** [comment]
@arkid 
Can you check without filter with the 3.8.3 release?
It should be fixed. There are still bugs when both the plugin 'Custom Bulk/quick edit' and 'Yoast SEO' plugin are enabled with Admin Columns Pro.

**Comment by adam-jones-net** [comment]
Thanks so much yes this seems fine now ;)

**Comment by tobiasschutter** [comment]
Great. 

The change to prio 200 did the trick.

`add_filter( "manage_{$this->page}-{$this->post_type}_columns", array( $this, 'add_headings' ), 200 );`

closed!
