### ISSUE TITLE
Use Dashicons where applicable

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#400]
Columns like "ping status" and "comment" status use external libraries. We should use Dashicons where applicable. Betters support over time and retina ready.

**Comment by DGStefan** [comment]
Famfam icons replaced by dashicons

**Comment by tobiasschutter** [comment]
ACF and Custom Fields need to fixed aswell.

Fixed: https://github.com/codepress/codepress-admin-columns/commit/3d06141c2b19f237b9ea6d23273d4a80923d6277
