### ISSUE TITLE
Continuous loading on Inline Edit when using select2 (e.g. with author)

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#401]
When you change an author you need to know which authors are available. Maybe it is more user friendly if we use both search and continuous loading for scrolling.

**Comment by DGStefan** [comment]
Todo
- [x] Show initial options for ajax search
- [x] Use pagination for ajax search for following types
- Author / Comment users
- Author name
- Column meta: title by id and user by id
- ACF: page link and post object(s)
