### ISSUE TITLE
Improved Custom Fields

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#41]
Add more fieldtypes:
- Text
- File
- URL
- Image: with the option to select ID or by URL
- Multiple Fields: with the option to select which field
- Post
- User
- Taxonomy
- Date
- Date Time
- Link

**Link column**
The idea behind this field type is to be used for custom fields that store URLs. When I select the Link type for this field, Admin Columns should automatically turn the displayed URL into a clickable link.

Extra options for this field type could possibly be:

- Ability to set a title for the link. So, instead of seeing the full clickable URL, I can tell it to display a link that says "Click to view" that has the URL as its href.
- Ability to select how to open the link, i.e., _blank, _self, etc.

**File column**
Output: Either icon or file name.

**Comment by DGStefan** [comment]
Link type added as described.
Refactoring of Custom Fields is still in a branche

Pullrequest: https://github.com/codepress/codepress-admin-columns/pull/76

**Comment by tobiasschutter** [comment]
related: https://github.com/codepress/admin-columns-issues/issues/182

**Comment by DGStefan** [comment]
- [x] new fields added
- [x] restyle interface
