### ISSUE TITLE
Sorting ACF field email not working

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#415]

**Comment by DGStefan** [comment]
Sorting on a ACF-email columns works fine.
But it seems that ACF sorting does not keep get_show_all_results into account.
Try to fix this with an extra metaquery check

**Comment by davidmosterd** [comment]
When get_show_all_results() returns true, the meta_query compare is set to 'OR' and takes into account empty values (both '' and NOT EXISTS).

I think it's a proper solution, though setting 'OR' on the meta_query impacts the entire query.
