### ISSUE TITLE
Make empty / Not empty optional

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#419]
![empty_label_option](https://cloud.githubusercontent.com/assets/2736280/13773154/2af8c5d4-ea98-11e5-882c-f5f827fe0a16.jpg)

related UI change: https://github.com/codepress/admin-columns-issues/issues/182

**Comment by DGStefan** [comment]
Not valid anymore after release Admin Columns Pro 4.0
