### ISSUE TITLE
Bulk editing support for inline edit

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#42]
It'd be really nice if one could select "multiple edits" as action, then tick of several users/posts/media and hit "Apply", and thereby saving same value to multiple items in one swift operation. Much like one can edit multiple posts with quick edit.

by Morten via helpscout

**Comment by abombelli** [comment]
Any news on this?

**Comment by DGStefan** [comment]
@abombelli 
No it is still a feature request. We wait for Tobias to make a decision about to add this feature or not.

**Comment by tobiasschutter** [comment]
Another approach to this: https://github.com/mcguffin/acf-quick-edit-fields

**Comment by DGStefan** [comment]
There is a revampp for inline edit planned for 2018.
It will be a complete new project, so we will close this request here.
