### ISSUE TITLE
Inline edit: when using select2 on custom field user colum only usernames are shown

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#420]
Use display name instead of usernames.
- Same for "Display Author As"

**Comment by DGStefan** [comment]
- Default is already Display name
- Display as is used for display in inline edit, this seems logic

**Comment by DGStefan** [comment]
related to https://github.com/codepress/admin-columns-issues/issues/467

**Comment by DGStefan** [comment]
Display is correct now.
New ticket for setting the display format for custom field user column.
