### ISSUE TITLE
Email support from plugin with diagnostics

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#43]
A email support form with diagnostics info. See Migrate DB Pro.
- Add error log (for API errors etc.)
- List of used plugins

![email_support_in_plugin](https://cloud.githubusercontent.com/assets/2736280/5417873/f636c1de-823d-11e4-9d7f-d1e86c1d4410.png)

**Comment by engelen** [comment]
Functionality implemented in branch https://github.com/codepress/admin-columns-pro/tree/in-plugin-support. Functionality to be implemented: list of active plugins.

**Comment by engelen** [comment]
List of active plugins (both site and network activated) implemented in https://github.com/codepress/admin-columns-pro/commit/c4e61a1c5ba4b3dee2484a55e66bfd812d9c1388. Needs testing and styling finetuning.
