### ISSUE TITLE
WooCommerce column: Expiry Date

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#446]
Expiry Date (this should automatically calculate 365 days from the order date and be inserted automatically)

**Comment by tobiasschutter** [comment]
You probably forgot to mention this is from a WooCommerce Extension, maybe WC Subscriptions? Because WooCommerce does not use expiration dates on orders.

**Comment by tobiasschutter** [comment]
related: https://github.com/codepress/admin-columns-issues/issues/223
