### ISSUE TITLE
Inline edit + ACF:+ Events plugin: term select issue

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#469]
With Events plugins: Term is not pre selected. And styling is wrong.

![image](https://cloud.githubusercontent.com/assets/2736280/14110756/29c65d44-f5c8-11e5-9e56-45e0ca2ea64e.png)

**Comment by DGStefan** [comment]
Styling (width) fixed.
There is a select2 conflict with the tribe event plugin on the posts overview.
A workaround is to disable the tribe select2 scripts on this specific overview with this filter

```
function cac_select2_tribe_events_conflict_fix() {
    $screen = get_current_screen();
    if( 'edit' == $screen->base && 'tribe_events' == $screen->post_type ) {
        wp_deregister_style( 'tribe-events-select2' );
        wp_dequeue_style( 'tribe-events-select2' );

        wp_dequeue_script( 'tribe-events-select2' );
        wp_deregister_script( 'tribe-events-select2' );
    }
}
add_action( 'admin_enqueue_scripts', 'cac_select2_tribe_events_conflict_fix', 100 );
```
