### ISSUE TITLE
WooCommerce column: order item meta

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#472]
Column which let you pick metadata from cphq_woocommerce_order_itemmeta. Similar to the Custom Field column.

**Comment by DGStefan** [comment]
@tobiasschutter 
I have a start of this columns but I cannot find a good case to add such a column.
An order can have the following order items (types)
- Line item (product)
- Shipping
- Tax
- Coupon
- Fee

Each line items can have their own metadata and there is not much overlap so it will be quite difficult to create a columns that shows exactly what you need.

Plans so far:
- User can select which order items types are displayed
- User can select which meta field (multiple?) are shown
- In overview show meta per order item (if available)
