### ISSUE TITLE
Allow columns to scroll horizontally 

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#49]
I often find that I set up a great admin interface using your plugin, but it does not scale to lower resolutions. Because all columns are percentage-based and the entire table is constricted to the width of the browser, layouts with many columns can quickly become too crowded.

One way to ensure a more consistent experience across all resolutions would be an option to set the table width in pixels and allow it to scroll horizontally. For example, my client may be working at a desktop resolution of 1024×768, but if I could set the table width to 1600px, I could ensure that they have room to see many more columns than the current configuration allows.

I did some digging in the inspector, and I think it would only require some minimal CSS:
```
.wp-list-table {
width: 1600px;// allow the user to define this value
overflow-x: scroll;// make this toggle available for each post type?
}
```

Topic: https://www.admincolumns.com/forums/topic/allow-columns-to-scroll-horizontally/

**Comment by engelen** [comment]
Allowing scrolling would interfere with the WordPress admin experience, in my opinion, but adding options for showing and hiding columns with be a good possibility. However, we need to think about how the decision should be made as to which columns to hide and show at what resolution. Allowing the users to specify this, might be a bit too much.

**Comment by tobiasschutter** [comment]
If users like to make their column horizontally scrollable they can use this snippet:

```
function my_wider_table() { ?>
    <style type="text/css">
    #posts-filter table.fixed { table-layout: auto; }
    #posts-filter table.wp-list-table {
        min-width: 3400px;
        overflow-x: scroll;
    }
    </style>
    <?php
}
add_action( 'admin_head', 'my_wider_table' );
```
