### ISSUE TITLE
Support for Multinetwork site table (network/sites.php)

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#490]
Forum ticket: https://www.admincolumns.com/forums/topic/multisite-networksites-php/

**Comment by tobiasschutter** [comment]
Possible columns:
- Site deactivated (data is stored in {prefix}_blogs and marked as deleted)
- Site archived ( same but marked as archived )
- Site metadata (edit > site settings tab). This data is retrieved from {prefix}_{blogid}_options

**Comment by stephanieleary** [comment]
I have a column request for the Sites table as well: total size of the site's uploads folder.

**Comment by tobiasschutter** [comment]
This made it into release 4.0:

- Sites Status
- Sites Options
- Sites Post count
- Sites Used plugins
- Sites Comment count
- Sites Current theme
- Sites Upload space used / total
