### ISSUE TITLE
Mobile issue when viewing WooCommerce Order screen

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#492]
WooCommerce order list does not display correctly on mobile

**Comment by DGStefan** [comment]
We have to decide if this is something we want to change in our plugin.
WooCommerce hides all columns except the order id column.
If we make a fix, we have to choose which columns we always want to be visible.

**Comment by DGStefan** [comment]
This does not seems to be an issue anymore since the new order revampp in WC 3.3
