### ISSUE TITLE
WooCommerce: Product attributes column

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#493]
Column that list only attributes for products (similar to variations)
- [x] Display
- [ ] Editing
- [ ] Sorting
- [ ] Sorting (nice to have)

**Comment by DGStefan** [comment]
@tobiasschutter 
We already have a Product Attributes column. Making it editable will be a challenge because a product can have a lot of attributes

**Comment by tobiasschutter** [comment]
The attributes UI can not be called from the overview without duplicating their entire code. This would be hard to maintain. Only if WooCommerce supplies a method for initialising their attributes UI should we consider supporting inline editing.

Sorting feature is rejected, what would we be sorting? I don't see a use case.

**Comment by Garconis** [comment]
@DGStefan What Product Attributes column are you referring to? The Product - Details one? This doesn't how in the export. :(

Edit: nevermind. I was thinking this is referring to the Order table, which is where I'm trying to find Variations.
