### ISSUE TITLE
Use better CSS revisioning

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#497]
Some webservers might ignore the ?version=x and serve a cached version. Maybe it's better to use the version in the filename or create a unique hash of the css contents as server the first 8 chars as the filename.

**Comment by tobiasschutter** [comment]
Is this really an issue? Caching requests on the admin side doesn't happen often. And if servers deliberately ignore the version tag, they would also have an issue with the complete backend when upgrading WP core, not just our plugin. I don't think this is something we need to support.
