### ISSUE TITLE
Feature: Visual Column Rearranging in overview

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#506]
I’d love to see a visual (meaning on the table screen) way of rearranging the column order without clicking over to the edit columns screen.

**Comment by tobiasschutter** [comment]
This could work. It would require an additional UI element, a button "arrange columns". Then by making the column header draggable, and storing it with ajax, we could make this possible. The re-arrange button could clutter the UI, maybe a settings option to hide this button is preferable. Similar to the "edit columns" button.

**Comment by DGStefan** [comment]
Duplicate
