### ISSUE TITLE
Optimize get_items for editable

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#533]
For each post we check the if an user can edit the post
This could be optimized for admins because they can always edit posts.

Ticket is related to HS ticket #2630
Just something to think about

**Comment by tobiasschutter** [comment]
related: https://github.com/codepress/admin-columns-issues/issues/763

**Comment by tobiasschutter** [comment]
Maybe we could use `edit_others_posts` as a preliminary check, and if fails do a `edit_post` check.
