### ISSUE TITLE
Option to remove all columns for column set

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#547]
Add a quick way to remove all columns to start from scratch.

**Comment by DGStefan** [comment]
@tobiasschutter 
We already have this filter
`add_filter( 'ac/enable_clear_columns_button', '__return_true' );`

Will this be enough or do you want to make this a feature/option?
Otherwise we can close this ticket.

**Comment by tobiasschutter** [comment]
Rejected
