### ISSUE TITLE
Create multiple setups of columns settings

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#56]
Let users create multiple column setups for the same type and label them. With a switch menu in the sidebar they can select the active column setup.

**Comment by abombelli** [comment]
+1

**Comment by tobiasschutter** [comment]
I created a branch for this.

**Comment by tobiasschutter** [comment]
We need exact use cases.

**Comment by abombelli** [comment]
Ideally we would like to set different column setups per post types.
Maybe in the edit view you could add a tab per setup.
This setups can then be selected in the admin list view via a drop down.

I hope this helps further, let me know you need any screens of a possible setup.
