### ISSUE TITLE
Feature request: Set default sorting per column set

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#563]
https://www.admincolumns.com/forums/topic/set-default-sort-option/
It would be great to set the default sorting preference.
that means: orderby and order. (set 1+ column and ASC/DESC for each Column Set)

So when you click on the 'reset sorting' butter, this new default sorting is set instead of the default or user saved sorting preference

Maybe add more settings for column sets like: filtering and number of pages. 
https://www.admincolumns.com/forums/topic/set-default-values-with-column-views/

**Comment by LukeAbell** [comment]
+1

**Comment by themightyant** [comment]
+1

**Comment by themightyant** [comment]
This would be really handy.  Whilst it is only a few clicks to sort the columns I have several sites that have many users and it would be great to be able to sort them by default rather than having to teach each user that sorting is prefferable.

**Comment by tobiasschutter** [comment]
Let's start by making this possible with a filter hook. I understand a UI option is preferable, but we don't want to clutter the interface. We have to give the UI part some more thought. Maybe an "advanced settings" section or something.

**Comment by themightyant** [comment]
A filter hook would ber great @tobiasschutter.  Fully understand UI / Clutter and time is needed for that.
Thanks for looking into it.

**Comment by marcorieser** [comment]
@tobiasschutter Anything new about this feature?

**Comment by tobiasschutter** [comment]
@marcorieser We have decided to implement a minimalistic version for the next release. We won't make any UI changes, but it will be available through a filter.

Work in progress:
- [x] Posts
- [x] Comments
- [x] Users

**Comment by tobiasschutter** [comment]
The new filter is named `acp/sorting/default` with 2 arguments. $orderby is the column name to order by. $list_screen is the `AC_ListScreen` object which can be used to target specific column sets.

In this example, I am targetting a specific column set called `5a267f01b8241` within a list screen. And the column with the following name `5a196e1ab2771` will be our default sorting. 

The Column set ID can be found in the URL:
![image](https://user-images.githubusercontent.com/2736280/34720046-a122926a-f53d-11e7-81b8-885383cb03c4.png)

The column name can be found by hovering over the Type label in the UI.
![image](https://user-images.githubusercontent.com/2736280/34719962-374eeb40-f53d-11e7-8bb8-630db57f2a5a.png)

Usage example:

```
add_filter( 'acp/sorting/default', function ( $orderby, AC_ListScreen $list_screen ) {

	// Column set (internally known as layout ID)
	$column_set = '5a267f01b8241';

	// Column name as stored in the DB
	$column_name = '5a196e1ab2771';

	// Display results in descending order?
	$descending = true;

	if ( $column_set === $list_screen->get_layout_id() ) {
		$orderby = array( $column_name, $descending );
	}

	return $orderby;
}, 10, 2 );
```

**Comment by tobiasschutter** [comment]
I will be working on a UI solution for a next release. This should allow the user to simply set a default sorting column without the use of a filter.

**Comment by Morgunov-Vitaly** [comment]
Hello, guys! We are waiting for the default sorting feature very much! What do you think, when it may be implemented?

**Comment by omikron** [comment]
Woocommerce orders do not have a Column set ID, how do you target them for a default sort?
