### ISSUE TITLE
WC Stock, Dimensions, Coupon usage and Price columns don't work with editable

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#567]
get_editable_value converts array to keys
- [x] AC_WC_Column_ShopCoupon_Usage
- [x] AC_WC_Column_Product_Price
- [x] AC_WC_Column_Product_Dimensions
- [x] AC_WC_Column_Product_Stock

**Comment by DGStefan** [comment]
Fixed for 4.0. 
Editable values converted to object instead of array
