### ISSUE TITLE
Multi site user filtering, sorting and editing support

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#571]

**Comment by davidmosterd** [comment]
The main issues is that MS User does not have the extra_table_nav function and a possible filter implemented.

I think adding a ticket to core is straightforward and I'll make sure this done by the end of next week. That way we can 'show' our customers we are working to get this going for them.

I'll take the ticket from here then.

**Comment by DGStefan** [comment]
@davidmosterd 
Please notice that all features are (and were) already possible for Multi Site users. We accidentally disabled these features in a previous release but it is activated again. Of course adding a ticket to core to add more support is an even better option. 

Currently, we place our filters in the footer and add them to the top with JS, which is not ideal.
