### ISSUE TITLE
Support Import/Export/Sync like ACF does

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#574]
Json import/export with hooks and filters

**Comment by jsrobinson** [comment]
This has been in the queue for a couple of years. Will this be coming soon?

**Comment by JoryHogeveen** [comment]
This is already possible right? Import/Export to JSON is but I don't know about syncing (or how this should work).

**Comment by DGStefan** [comment]
@JoryHogeveen 
No this is not yet possible, at least not like ACF does.
You can export the settings to JSON and import them with the import feature, but we don't have something that automatically does this for you.

@jsrobinson this is still not something that is on our roadmap at this moment, but since this is something that I hear often, I will discuss this again within the team.

**Comment by DGStefan** [comment]
We did this with Local Storage

**Comment by tobiasschutter** [comment]
More info on Local Storage and how to set it up: https://www.admincolumns.com/documentation/local-storage/
