### ISSUE TITLE
Make Sorting available for Taxonomy overviews

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#578]
- Custom columns
- ACF Fields

Would it help if I were to use the built in WP Term Meta functionality?

**Comment by mostlyharmless2024** [comment]
This would be an extremely useful feature for the application we're working on. We use ACF fields on custom taxonomies/terms for a lot of our data but none of it is currently sortable or filterable.

Sidenote- I'm not sure ACF is using the built in Term Meta functionality of WordPress yet, I had to use the 'acf/update_value' filter to save Term Meta data whenever certain ACF fields get updated.

**Comment by DGStefan** [comment]
Duplicate and almost ready
https://github.com/codepress/admin-columns-issues/issues/1030
