### ISSUE TITLE
Recognize other URL structure for Custom post types for AC_ListScreen

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#579]
At this moment we always look for the default WordPress url structure for Custom post types like edit.php?post_type={}

There are plugins that uses other structures like WpJobboard.
It uses this structure admin.php?page=wpjb-job

Now it is not possible to add or recognize columns for this overview.
Ticket: https://www.admincolumns.com/forums/topic/wpjobboard/

**Comment by tobiasschutter** [comment]
This can already be achieved by extending the AC_ListScreen object. The 'page' var should be 'wpjb-job'. A good example is the MLA add-on: https://github.com/codepress/ac-addon-mla.

No update to our code is necessary, so closing.
