### ISSUE TITLE
External Link column

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#581]
External link column which display the number of external links in it's body content.

**Comment by philipstancil** [comment]
This would be incredible.

**Comment by tobiasschutter** [comment]
related: https://github.com/codepress/admin-columns-issues/issues/580

This could be achieved by using AC_Column_AjaxValue in combination with an autoload feature.

**Comment by DGStefan** [comment]
I think that both the internal and external link count could be combined into 1 column

**Comment by tobiasschutter** [comment]
@DGStefan Could you make it non-ajax?
