### ISSUE TITLE
Make setting for fixing the column headers on top of the table

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#582]
HS ticket 2795

Context:
Hey! I'm curious if there's a way to fix the WP > Pages column headers to the top of the page? We're using 16 columns right now, so it's super easy to get confused about what's what as we scroll down the page. Furthermore, we work on bigger sites, so we display 200 pages at a time. This makes for a lot of scrolling if we can't remember which column is which.

**Comment by tobiasschutter** [comment]
Out of scope. Maybe in a separate plugin.
