### ISSUE TITLE
ACF Addon: Support new ACF Clone field

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#587]
Investigate and find a solution to add support for the new ACF clone field

**Comment by DGStefan** [comment]
Moved to ACF repo
https://github.com/codepress/ac-addon-acf/issues/71

**Comment by kernandlead-dev** [comment]
Hi @DGStefan thanks for the great plugin. is ee you just removed this from `Future Release` but I don't have access to codepress/ac-addon-acf#71

I just updated to the most recent version of the PRO plugin, but still not seeing cloned fields in my options for Admin Columns Pro. 

Thank you would appreciate any feedback

**Comment by tobiasschutter** [comment]
The issue has been moved to a private repo, but the good news is that issue is almost finished and ready for release.

**Comment by officialsuyogdixit** [comment]
> The issue has been moved to a private repo, but the good news is that issue is almost finished and ready for release.

Any update after one year? I want to purchase the PRO and ADDONS. But just wondering about this.
