### ISSUE TITLE
Natural sorting in MySQL

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#588]
The sorting algorithm of MySQL is great for numerical or alphabetical data, but those two combined are not sortable by default. There are a few articles on the subject (like this one: http://skybluesofa.com/blog/how-implement-natural-sorting-mysql/).

It's not a big issue as we can always fall back to PHP sorting which supports natural sorting just fine, but MySQL would be better performance.

**Comment by tobiasschutter** [comment]
@davidmosterd can you close this one or assign it to a release milestone?
