### ISSUE TITLE
Support post overview for plugin that don't use the default custom post type page

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#593]
Some plugin use there own page to display the WP List table.
URL are like edit.php?page={}
Look for a way to support these page structures

Plugins:
https://wordpress.org/plugins/custom-field-bulk-editor/

**Comment by tobiasschutter** [comment]
The problem with custom pages is that they use custom list tables. These custom list tables use their own filters for displaying the column's value. Or sometimes they don't have a custom filter at all. A generic way to support them won't be possible.

We [solved this](https://github.com/codepress/ac-addon-mla) for MLA ( Media Library Assistant ) by creating it's own AC_ListScreen object and using their custom filters.

**Comment by DGStefan** [comment]
This would requite custom ListScreens
