### ISSUE TITLE
Inline Edit for not existing custom field

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#597]
Make it possible to select/create a not existing custom field that can be used with inline edit.
This way you don't need to have at least 1 post/user/taxonomy field with a value for that specific field.

**Comment by tobiasschutter** [comment]
Add a "create new field" option to the select menu:
![image](https://user-images.githubusercontent.com/2736280/29169480-8561946c-7dd4-11e7-9a7a-920dac298184.png)

**Comment by DGStefan** [comment]
Better to create a way to add a Custom Field Column for non existent custom fields (already an issue).
