### ISSUE TITLE
Filter by Past and Future dates

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#60]
Two additional filter options for date to be able to select all future and past dates.

![events-filter](https://cloud.githubusercontent.com/assets/2736280/5611148/cf704092-94c2-11e4-8439-baffaae7196a.png)

by Claudius

**Comment by tobiasschutter** [comment]
Start with ACF date fields.

**Comment by DGStefan** [comment]
Pullrequest send
