### ISSUE TITLE
Add "Download File" column to media library storage model

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#618]
Interesting suggestion by @jpelker at WP.org support forums (https://wordpress.org/support/topic/suggestion-for-media-columns-download-link/)

"This is a small suggestion for the Media Library columns: Creating a new column that’s provides a link to download the attachment.

Alternatively, there could be a permalink within the “Full Path” column. The “Actions” column could also use a download button."

**Comment by tobiasschutter** [comment]
In progress: https://github.com/codepress/codepress-admin-columns/tree/618-download-column
