### ISSUE TITLE
Cell CSS classes based on value

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#62]
Add CSS classes to cells based on value (e.g. .cpac-cell-price-34) for a column called "Price" and a post with price "34". We could also implement this using data attributes with the raw value of the column. Probably addon-terriotory.

**Comment by tobiasschutter** [comment]
- There should be a maximum length for this classname
- The raw value would need to be retireved twice, this should be optimized
- Let's only enable this with a development filter.

**Comment by tobiasschutter** [comment]
We will add a developer filter for its classname.

**Comment by engelen** [comment]
Class names are hardcoded into `WP_List_Table` class; unfortunately, we can't properly circumvent WordPress' default behaviour here. Closing as wontfix.
