### ISSUE TITLE
Editable settings per row

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#624]
See if it is possible to set editable options for a specific row/post.
Related ticket
https://www.admincolumns.com/forums/topic/acf-load_field-filter-problem-when-i-use-global-post-data/

**Comment by tobiasschutter** [comment]
The editing data comes from the `get_view_settings` method, which is not post specific. The dropdown options are populated per column type, not post + column type. Because the use case for this a so limited, and the necessairy changes would be quite extensive, we won't be implementing this.
