### ISSUE TITLE
When using bulk edit, extra unused post formats are created that should be not available in filtering

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#644]
Related topic on website
https://www.admincolumns.com/forums/topic/post-format-set-wrong-or-gone-inline-edit-bulk-editing/#post-12454

It only happens when you use bulk edit. We first have to investigate why these extra formats are created and filter them in our filter dropdown. Or we can show all available formats in the dropdown by using the WordPress function instead of looping through all posts to see which formats are used.

**Comment by tobiasschutter** [comment]
It seems that it's a WordPress core issue. Even with AC disabled I can reproduce this bug.

To reproduce:
1. Go to post screen.
2. Select two posts (checkboxes) and select the "Edit" under Bulk Actions at the top.
3. Select "Chat" as post format, and click update.
4. Select the same two posts (checkboxes) and select the "Edit" under Bulk Actions at the top.
5. Select "Video" as post format, and click update.

Check the DB term table and order them by latest term_id. The top row now has a new term with the slug "chat", which is linked to the taxonomy "post_format". This was created by using Bulk Edit as described above.

Seems like a core bug to me.
