### ISSUE TITLE
Quick Edit issues since 4.7

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#645]
Related topics
https://www.admincolumns.com/forums/topic/columns-size-error-after-saving-quick-edit/#post-12458

Issues
- Quick edit fields are not populated when the title column is not available
- Quick edit fields are not stored when the title column is not available

**Comment by davidmosterd** [comment]
Fix applied for post_types and comments. Ready to test.

**Comment by DGStefan** [comment]
@davidmosterd 
Fixed for Post types.

Problem still exists for taxonomy quick edit

**Comment by DGStefan** [comment]
Issue fixed for post types and taxonomies

Not fixed for the comment because there is no nice way to get the correct quick edit markup from the comment list screen. Workaround for comment to use quick edit is to add the default primary column which is the comment column.
