### ISSUE TITLE
WooCommerce Orders overview: Make it possible to filter orders based on product category

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#653]
**Suggestion**
Create a column that shows the product categories for an order.
It would be great if we can filter on this column

**Related**
https://github.com/codepress/admin-columns-issues/issues/652 (closed)

**Comment by tobiasschutter** [comment]
This would need a pretty complex filter query which could cause performance issues. It also seem a pretty unique use case. How beneficial would this be and to who?
