### ISSUE TITLE
Support to change the values for Custom Field Booleans

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#657]
It would be nice if you could change the default behavior in Inline edit for Boolean fields. It now stores 0/1 but yes/no true/false can also be possible values.

https://wordpress.org/support/topic/checkmark-and-value-yes-no-in-db/

**Comment by tobiasschutter** [comment]
We choose to store boolean as 0 and 1. Any other formats are not supported for CF Booleans.
