### ISSUE TITLE
Set default filtering per column set

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#659]
It would be great if you can set a default filter on a column. If you open an overview page, the filter is active without having to select it.

--update
HSTicket3703
Is it possible to add a fixed filter to a Columns-Set?
We would have two scenarios here:
- A static filter is defined for a column-set. The user may not change the value in the post-overview which is used to filter the set (Static)
- A predefined filter for a column-set that is automatically applied as long as the user does not change the filter-value. (Changeable)

**Comment by Habichtsberg** [comment]
I would suggest to add this feature as a "plugin" as "WooCommerce" and "ACF".
So the user may decide, if he wants this bit more of complexity if required.

**Comment by tobiasschutter** [comment]
We won't be actively developing this. The idea is very neat, but it would only apply for a very select group of users. Anyone who would like to create a plugin for this is welcome to. We would happily support this and make any changes necessary to our code if needed.
