### ISSUE TITLE
Inline edit: remove inline-edit-click event for title maybe?

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#66]
by Joel
If I have inline edit activated, is there anyway to allow for still clicking into the article / page - because when you click the hyperlink of the title of the article and page it just pops up your inline edit tool. Inline editing is cool, but I think it would make sense to regulate the title hyperlink to just the pencil icon.

by Tobias
We delibrately choose to make the title use inline edit on clicking to make the inline editing faster and a bit more intuitive for the user. The drawback is exactly what you mentioned, it changes the expected event. Maybe we will also introduce a developer filter to turn it off.

**Comment by engelen** [comment]
This will require some further work; a proper way to do this would to specify both the selector for the placement of the edit icon, and the selector for the actually editable element.

**Comment by DGStefan** [comment]
Links inside the editable content are now clickable
https://github.com/codepress/admin-columns-pro/pull/37
