### ISSUE TITLE
ACF Repeater column: Show Count Rows

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#663]
https://www.admincolumns.com/forums/topic/acf-repeater-count-rows/

I like using of ACF Repeater fields but not always I want to display one subitem. Many times there is e.g. photos attached to product, timetable frames attached to course or support documents attached to incident. For me also showing “number of rows in repeater fields” as sortable/fitlerable value will be good feature.

So my feature request is to allow choose virtual Sub Field “Number of Rows” for Repeater Type of ACF field in admin column configuration.

**Comment by pkiula** [comment]
Was this ever done?

**Comment by tobiasschutter** [comment]
Yes, this was merged in 2018. 
![image](https://user-images.githubusercontent.com/2736280/60893032-70878300-a260-11e9-8fe3-464fc0d3f002.png)

**Comment by pkiula** [comment]
Doesn't work. I see nothing that shows me "Number of Rows". I see a "Number of Fields", which is not what I need -- it shows me 1 no matter how many repeatable rows are added. What am I missing? 

![image](https://user-images.githubusercontent.com/2611511/60899549-a9136680-a238-11e9-9c14-40ad512a50ee.png)

Unless of course this requires Admin Columns Pro, which is sad. This is fairly basic functionality.

**Comment by tobiasschutter** [comment]
It's part of the ACF add-on, which is available for Admin Columns Pro.
