### ISSUE TITLE
ACF Flexible content field improvement

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#672]
It now only shows the count of the used flexible content fields.
There is an ACF filter that can alter the label of the field and we can use this to show for each found flexible content field.
https://www.advancedcustomfields.com/resources/acf-fields-flexible_content-layout_title/

But since it is the only way to change the label for a field, this may be a too specific use case.

**Comment by tobiasschutter** [comment]
Implement with AC_Column_AjaxValue
