### ISSUE TITLE
Mutex options

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#694]
It might be cool to have inline edit support a mutex for true/false and numeric fields (other fields might have use-cases too).

The idea is to add an option that says this field holds the mutex for all records on a certain field. When you toggle the value, the other field is disabled. That way you can for example say: default supplier, primary resource, winner, etc. 

It's a complex use-case with lots of nasty things to consider, but there is a use-case so it's here.

**Comment by DGStefan** [comment]
I would say, way too complex for the GUI, but greatly solvable with our available hooks.
