### ISSUE TITLE
Only show upgrade notification to administrators (and not to regular subscribers, editors, etc.)

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#698]
From https://wordpress.org/support/topic/limit-notifications-2/. Only show Admin Columns Pro notifications for users who can `manage_options` (`current_user_can('manage_options')`). Check other notifications within Admin Columns as well to make sure they're only displayed for users with the right premissions.

**Comment by tobiasschutter** [comment]
Since AC 3.0 we now check for both capabilities: 'manage_admin_columns' and 'install_plugins' before showing any notifications
