### ISSUE TITLE
WooCommerce Attributes Redirect to Home Page

### ISSUE THREAD

**Issue by aibrean** [codepress/admin-columns-issues#724]
I've got the latest (4.0.1/2.0 ACF/2.0 Woo) installed. I noticed this issue with the 4.0 release (I also have WC 3.0 installed) where having the WooCommerce add-on with attributes in the list results in the list page (i.e. all products) redirecting to the website's home page.

**Comment by DGStefan** [comment]
@aibrean 
Do you still have this issue with the current version of the WooCommerce add-on?
We updated the WooCommerce addon to work with WooCommerce v3.
We cannot reproduce this issue on our own environments.

**Comment by aibrean** [comment]
@DGStefan I can confirm that it's working now.

**Comment by DGStefan** [comment]
@aibrean 
Great I will close this ticket.
