### ISSUE TITLE
Filtering in combination with "Search Everything" causes filter button to be pressed twice

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#727]
The plugin "Search Everything" (https://wordpress.org/support/plugin/search-everything) can cause issues when filtering is enabled.

Looking to reproduce the problem but this is how it was triggered on a production installation:

* Have a filter for status (taxonomy)
* Press filter
* See 'no results'
* Press filter 
* See the actual results

Mind the ?s in the URL.

**Comment by tobiasschutter** [comment]
Moved: https://github.com/codepress/admin-columns-pro/issues/344
