### ISSUE TITLE
Inline Editing - "modal" only partly visible on first column if content is "short"

### ISSUE THREAD

**Issue by quasel** [codepress/admin-columns-issues#732]
1) activate inline editing for post title, keep it as first column
2) set an short title
3) try to inline edit 

Tested in Safari&Firefox
WordPress Version: 4.7.3
PHP Version: 7.0.17
MySQL Version: 5.7.17

![ohne titel](https://cloud.githubusercontent.com/assets/9464217/24755557/0ba2696e-1adb-11e7-8d2e-f36c7995f496.png)

**Comment by DGStefan** [comment]
Already fixed in 4.0.3
