### ISSUE TITLE
Sorting / Filtering bug for removed column

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#737]
When you have filtered on a column and remove the column, it is not visible that sorting is still done on the removed column. You will get no results when you filter afterwards on another column. The only indication that there is sorted in that case, is because you can see the 'reset sorting' button on top of the overview.

We should do a check if a column exists when sorting is still set as preference for a non existent column.

**Comment by tobiasschutter** [comment]
Check for array and if column exists (from orderby) on ACP_Sorting_Addon::get_sorting_preference
