### ISSUE TITLE
Filter dropdown fallback for a max number of options

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#755]
We can limit the maximum number of options for a filter dropdown.
When this number is exceeded, we can show a label 'limited to...' or we could change the selectbox to a textfield. Maybe even improve it with select2.

**Comment by davidmosterd** [comment]
+1 ;)

**Comment by tobiasschutter** [comment]
This issue is no longer relevant since the introduction of smart filtering
