### ISSUE TITLE
Multisite install does not recognise updates in managewp.com

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#782]
HS Ticket 4175

I have never had any problems before and it works just as it should with normal sites but for some reason the update is not recognized for multisites via ManageWP. 

The Admin Columns Pro update is visible in the WordPress admin for both the normal site ad the multisite. The normal site and the multisite is hosted at the same company and we are using PHP 7.1.4 and more or less the same plugins. I have talked with ManageWP but they are blaming caching but since we aren't using any object cache and it works with all other plugins I doubt that explanation. 

We've had a similar problem in the past with another premium plugin where there was an issue with normal admin and superadmin permissions on multisites. We've also had the free Admin Columns 2 installed on several multisites without problems but then Admin Columns have been activated per subsites and not network activated. Any ideas why it's not working to update via ManageWP? You can set up a test account for free at ManageWP if you want to test yourself.

**Update**
Problem can be reproduce by using WP-CLI and activate the plugin.
I suspect that the the 'register_activation_hook' does not run. So the ACP capability is not set.

**Comment by davidmosterd** [comment]
Can be tested.

Also needs testing on multisite, as there is no separate function for this anymore.

**Comment by DGStefan** [comment]
Tested on clean install
