### ISSUE TITLE
All fields with before and after options

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#8]
All fields with before and after options, I used this to put some html like field or and other stuff.

http://www.admincolumns.com/forums/topic/a-list-of-features/

**Comment by engelen** [comment]
I don't particularly support this feature request. Most fields simply don't need before- and after-options, and we should try to adhere to the "decisions, not options"-principle. Showing them for custom fields is useful, but it isn't for other fields.
