### ISSUE TITLE
Comment filtering PHP 7.1 issues 

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#804]
https://www.admincolumns.com/forums/topic/custom-meta-filter-integer-php7-1/

Adding a custom column based on a custom meta field type integer trying to filter a range gives a fatal error.

Error only seems to occur in PHP 7.1

Fatal error: Uncaught Error: [] operator not supported for strings in /WordPress/plugins/admin-columns-pro/classes/Filtering/classes/Model/Meta.php:130 Stack trace: #0 /WordPress/plugins/admin-columns-pro/classes/Filtering/classes/Model/Meta.php(158): ACP_Filtering_Model_Meta->get_filtering_vars_ranged(Array, Array) #1 /WordPress/plugins/admin-columns-pro/classes/Filtering/classes/Strategy/Comment.php(17): ACP_Filtering_Model_Meta->get_filtering_vars(Array) #2 /app/wp-includes/class-wp-hook.php(298): ACP_Filtering_Strategy_Comment->handle_filter_requests(Object(WP_Comment_Query)) #3 /app/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #4 /app/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #5 /app/wp-includes/class-wp-comment-query.php(386): do_action_ref_array('pre_get_comment...', Array) #6 /app/wp-includes/class-wp-comment-query.php(357): WP_Comment_Query->get_comments() #7 /app/wp-includes/comment.php(226): WP_Comment_Query->query(Array) #8 /app/wp-admin/includes/class-wp-comments-list-tab in /WordPress/plugins/admin-columns-pro/classes/Filtering/classes/Model/Meta.php on line 130

**Comment by DGStefan** [comment]
This issue is bigger then just the filtering issue mentioned here. We have to check all our code if it is compatible with PHP7.1. 

Related information:
https://www.drupal.org/node/2825841#comment-11769751

**Comment by hjanuschka** [comment]
@DGStefan i originally reported this issue, is that already resolved/released as milestone 4.0.5 is finished?

i am not 100% sure how to follow development, and get notified once issues are resolved? , as rolling back to a version below php7.1 on production is not possible in my situation.

and right now the filtering of the paid version is broken, any chances we get a hotfix release?

**Comment by DGStefan** [comment]
@hjanuschka 
Yes we were able to reproduce the issue and made a fix in 4.0.5.
Our 4.0.5 version is just out and when you update the plugin the fix should be applied. Can you test this and let us know if this issue is fixed?

**Comment by hjanuschka** [comment]
saw it on the download page that there is an update 👍  (cant run auto-update here on my servers)
i tested it and it worked 🙏  thx for your quick response and fix.

**Comment by davidmosterd** [comment]
I have looked into this issue also and it seems AC is making a wrong assumption on how to treat default WP options. We assume an array, which is the case 9 out of 10 times, but we should always make sure its compatible / has run once through ```wp_parse_args``` to remove the odd case of a empty string or even a query style argument like  ```a=1&b=2```

The solution should be something like running ```wp_parse_args``` once before we add our own parameters.

**Comment by DGStefan** [comment]
https://github.com/codepress/admin-columns-pro/commit/bbe09c0f754f765a3987c904ec89b325747009bd
