### ISSUE TITLE
Author Custom Field Column

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#811]
Create a column that can show custom fields for a posts author.
We already have a user custom field column for the WooCommerce order overview page.
This is a very good base for implementing it for the author field.

Branch: https://github.com/codepress/admin-columns-pro/tree/811-author-custom-field

**Comment by tobiasschutter** [comment]
Maybe we could add a display option "Custom Field" to the user/author settings. That way every column that formats the user will have this.

**Comment by DGStefan** [comment]
@davidmosterd 
Could you have a look at the pull request?

**Comment by tobiasschutter** [comment]
Testing is done. Changed syntax a bit and optimised sorting.
