### ISSUE TITLE
Left border of input elements in ranged filtering is too short

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#813]
The CSS class `.acp-range .input_group input` has a white top and bottom border of 1px, which makes the ranged input look kind of funny. Setting `border-top-width` and `border-bottom-width` of `.acp-range .input_group input.min` and `.acp-range .input_group input.max` to 0 should do the trick.

![image](https://user-images.githubusercontent.com/2271433/26932666-6d7bc364-4c64-11e7-8746-9abbdde7241c.png)

**Comment by DGStefan** [comment]
@engelen 
In which browser did found this issue?
I cannot reproduce this issue in Chrome, Firefox or Safari on a Mac.

**Comment by engelen** [comment]
Chrome 58, WordPress 4.8, AC 4.0.5, AC-ACF 2.0.4. It's difficult to notice, but it's definitely there :-).

**Comment by DGStefan** [comment]
@engelen 
I was able to reproduce the issue, only when I zoomed in the page with a specific percentage.
Patched the CSS with your input and merged this change for the upcoming maintenance release.
