### ISSUE TITLE
Related taxonomies column

### ISSUE THREAD

**Issue by JoryHogeveen** [codepress/admin-columns-issues#815]
This was working in earlier versions but since 3.x the column types are different.

While 3.x supports related posts, media and user items it doesn't support taxonomies anymore.

I'm using Pods and with the multiple values it shows all data from the related object (probably because pods returns the full related object as an array instead of an ID).

Again, this was working fine in 2.x!

**Comment by DGStefan** [comment]
@JoryHogeveen 
Are you aware that we have a specific integration add-on for Pods?
The solution we had in the 2.x version was specifically written for Pods, and we decided to move all integration logic to a specific plugin.

You could consider to write your own logic for this specific feature by using this filter:
https://www.admincolumns.com/documentation/filter-reference/ac-column-value/

If you need any help with that, please try to contact me at our live-chat on our website. Or you could of course consider to upgrade to our pro version and use our integration add-on for Pods.

**Comment by JoryHogeveen** [comment]
Hi @DGStefan 

Yes I am very aware, though I'm using the free version for this site and the Pods integration is premium.
So, why was this part removed from the free plugin?
