### ISSUE TITLE
Sorting and Filtering on (two different) Taxonomy columns gives an error

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#818]
Reproduce the issue
- Create two different Taxonomies columns
- Filter on column A
- Sort on column B

This will give an SQL error:
[Not unique table/alias: 'wp_term_relationships']

**Comment by DGStefan** [comment]
@davidmosterd 
Can you have a look at this?

**Comment by tobiasschutter** [comment]
I could not reproduce this issue. Which exact column did you use? A native column or the "Taxonomy" column.

**Comment by davidmosterd** [comment]
I have reproduced the issue and wrote a fix. It seems that using the MySQL "USES" does not take your alias into account; so I have added a sorting alias to the taxonomy query and written out the "USES" to "ON" statements. Seem to work fine now filtering & sorting and just sorting. 

Ready to be deployed in the next release.
