### ISSUE TITLE
Custom field text area displays "..." instead of the actual text

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#821]
Custom field text area displays "..." instead of the actual text. 

I haven't been able to reproduce the issue yet. Could have something to do with how the Word limit or Char limit are being applied. Or maybe the string contains HTML tags that are being cropped by `trim_characters` too strict.

**Comment by DGStefan** [comment]
I can reproduce this issue when you have a link at the start of the value. I think that if you want to use the char or word limit, we have to strip the tags before we do this.
