### ISSUE TITLE
Pods Advanced Content Types support

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#822]
See if we can support the Pods Advanced Content Types.
http://pods.io/docs/learn/what-are-advanced-content-types/

**Comment by DGStefan** [comment]
There will be no support for Pods Advanced Content Types because it is simply not possible.
Pods does not use the default WP List Table for the ACT so it not possible to use the default hooks to make Admin Columns Work with these overview pages.

**Comment by JoryHogeveen** [comment]
There is a chance that this might be possible once Pods 2.8 gets out.
