### ISSUE TITLE
Media screen small style issue

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#830]
Margin is missing between "reset sorting" and "apply"

![image](https://user-images.githubusercontent.com/2736280/27820312-5e078dc0-609e-11e7-87c9-37919ff5095f.png)

**Comment by DGStefan** [comment]
https://github.com/codepress/admin-columns-pro/commit/8614baf2b676ee728f0f8da70d4a8dfc2ebef1b9
