### ISSUE TITLE
Sorting posts give an sql error in combination with Yoast SEO

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#844]
Error:
`SELECT wp_posts.ID FROM wp_posts WHERE 1=1 AND wp_posts.ID IN (229,240,165) AND wp_posts.post_type = 'post' AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) LIMIT 0, -1`

Reproduce:
Install Yoast SEO 5.0
Add Excerpt column to post
Sort on excerpt

It seems Yoast SEO hooks into the wp_query and adds `-1`

**Comment by DGStefan** [comment]
https://www.admincolumns.com/forums/topic/yoast-seo-and-admin-columns-pro/
