### ISSUE TITLE
Fixed column in horizontal scrolling

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#854]
https://www.admincolumns.com/forums/topic/allow-fixed-bar/
When you enable horizontal scrolling, you might want to see a default column all of the time, for example the ID or the title. Or you could use the primary column and always make it visible by giving it a fixed position in the horizontal table.

**Comment by worldtravlr** [comment]
Would love to se this feature and can't seem to be able to do it via CSS.  Any timeline on this?

**Comment by tobiasschutter** [comment]
Moved: https://github.com/codepress/admin-columns-pro/issues/359
