### ISSUE TITLE
Possible fatal php error on WC add-on when searching products

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#857]
aaltomeri reported the following through slack:

`Fatal error: Uncaught Error: Call to a member function is_type() on boolean in plugins/admin-columns-woocommerce/v3/classes/Editing/Product/StockStatus.php:19`

Sometimes `get_edit_value` return invalid products, causing a fatal. This can happend when using the search. It could be caused by a plugin altering the search query maybe. Or the returned query results are not all WC_Product objects. 

A solution would be to always check for a valid WC_Product object on `get_edit_value`.

**Comment by thomasmery** [comment]
Hi,

so it was caused by some search results returning non-products
due to an altered search query by a custom plugin

this is fixed on my end and all works as expected

thanks

**Comment by DGStefan** [comment]
@thomasmery 
thanks for the feedback!

@tobiasschutter 
What do you think, do we have to change this in our product? Normally you only get existing products on this overview so why adding some extra checks. Can you make a decision or close this ticket?

**Comment by tobiasschutter** [comment]
This was clearly caused by a 3rd party plugin. Issue closed.
