### ISSUE TITLE
Display max number of items

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#867]
For example a max number of attachments. If you have 10 attachments attached to a post, you might only want to show 4. By adding a clickable "count of items" we can display the rest.

![image](https://user-images.githubusercontent.com/2736280/28644020-1a25c1f0-7258-11e7-87c9-d3d913d9c65c.png)

**Comment by DGStefan** [comment]
Related issue
https://github.com/codepress/admin-columns-issues/issues/311

There is already a pull request for this change

**Comment by tobiasschutter** [comment]
Columns:
- [x] Attachments
- [x] Custom Field: Images
- [x] ACF: Gallery

Maybe we could use this setting for Relationships (post etc.) as well.

Which columns are also good candidates?
