### ISSUE TITLE
Remove Post Roles column

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#871]
Remove Post Roles column in favour of Author column with added roles option

**Comment by tobiasschutter** [comment]
Remove AC_Post_Roles column. Needs a DB update script.

**Comment by davidmosterd** [comment]
Patch submitted. Wrote a database update script for 3.0.7 that updates this column. For testing purposes the roles column itself is not yet removed **NEEDS TO BE DONE AFTER TESTING**

Affects only the free.

@tobiasschutter @DGStefan Can someone also test this?
