### ISSUE TITLE
ACF Support for new field type Groups

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#894]

**Comment by DGStefan** [comment]
Started with a new Format Interface for fields that don't use any settings that can format the value. This works for both the Repeater field as for the new ACF Group field

https://github.com/codepress/ac-addon-acf/compare/894-group-subfield

**Comment by tobiasschutter** [comment]
Currently "Groups" can be displayed. We should also built-in support for the pro features. A refactor will be needed.

**Comment by DGStefan** [comment]
Moved TO ACF
