### ISSUE TITLE
Filtering TableScreen vs Model for requests

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#909]
Right now the filtering model depends on an active TableScreen in order to work properly. This is a very tight coupling that might not be needed and disallows a filter model to be instantiated without a functional TableScreen.

What might be better is that each model can decide whether is being filtered or not based on the input it gets (from either a request or by a setter). In the first version, we could simply work by asking the $_GET parameters, but it would be even better to inject a Request object with the model to work with. 

The methods involved now are:

get_requested_filter_values
get_requested_filter_value
get_request_var (to a lesser extend)
get_request_var_column (seems scopecreep to me, the model could do this?)

**Comment by tobiasschutter** [comment]
Moved: https://github.com/codepress/admin-columns-pro/issues/363
