### ISSUE TITLE
CSV Export: Support for native columns

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#927]

**Comment by engelen** [comment]
Native columns (e.g., Title, Date, Author) are currently supported by implementing a custom exportability model for each of them. It's not possible to automatically fetch the value of native columns even somewhat elegantly, as far as I remember from the development of the main plugin.

Or did you mean something else, @tobiasschutter?

**Comment by engelen** [comment]
Closing; as we discussed today, third-party columns should be implemented with the `do_action` call for custom columns. See https://github.com/engelen/cac-addon-export/issues/5.
