### ISSUE TITLE
CSV Export: How do we want to test functionality?

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#929]
@davidmosterd @tobiasschutter 

For the exporting plugin, there's quite a few columns that have to be tested. I have been thinking about what a good, consistent way of doing this would be. Now, I remember there were some testing suites available with dummy columns, including columns for ACF/WooCommerce. Are these available? And what do you currently use for testing, e.g., proper column output?

**Comment by tobiasschutter** [comment]
Our dummy settings plugin will setup most columns for you: https://github.com/codepress/acp-dummy-column-settings. For ACF it will work out-of-the-box.

For WooCommerce you can install Dummy Content: https://github.com/codepress/dummy-content. It can create products and orders for you.

**Comment by engelen** [comment]
That sounds like a good solution! I've tested it, and it works well for testing exporting functionality. In the future, we might want to consider unit testing for this.
