### ISSUE TITLE
Comment Count column does not support get_raw_value

### ISSUE THREAD

**Issue by engelen** [codepress/admin-columns-issues#936]
Unlike (almost?) all other non-default columns, the post "Comment Count" column does not support retrieving its raw value. This is necessary to support external add-ons (e.g., exporting).

**Comment by DGStefan** [comment]
@engelen This column does not need a get_raw_value (except for export) and this method is not a 'must' for a column. It's convenient for sure, but we decided not to implement the raw_value for this column.
