### ISSUE TITLE
Support Date Time editing for existing columns

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#944]
Check repo for columns that could change the date type to datetime
**Posts**
- [x] Post Date
- [x] Publish Date

**Media**
- [x] Date

**Comment by tazeverywhere** [comment]
Hi,
Would it be possible to also have `date time` editing for personal field type ?
Actually only `date` is selectable.

<img width="743" alt="capture d ecran 2017-11-25 a 20 18 14" src="https://user-images.githubusercontent.com/4191041/33233904-fcb44f44-d21d-11e7-866e-acd2cc576811.png">

Anyway, thx for this awesome plugin !
All the best.
