### ISSUE TITLE
 Remove `ACP_Column_Post_Comments` after cac-addon-woocommerce 2.1.6 release

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#949]
Remove `ACP_Column_Post_Comments` after cac-addon-woocommerce 2.1.6 release because of dependencies

**Comment by DGStefan** [comment]
@tobiasschutter 
Since the new export feature, the column is not obsolete anymore.
This Pro column now has a purpose for loading an export model.
