### ISSUE TITLE
HELP!! Fatal error: Call to undefined function apply_filters_deprecated() in 

### ISSUE THREAD

**Issue by hanne3w** [codepress/admin-columns-issues#958]
**Fatal error:**   ###
Everytime I try to log in on my WordPress website i get this: Fatal error: Call to undefined function apply_filters_deprecated() in /
I have no idea how to fix it as i cannot even get in to the website.

**Comment by tobiasschutter** [comment]
Hi, we do not use `apply_filters_deprecated` in our code. It must be triggered by another plugin.

You could try disabling all plugins and enable them one-by-one to find the culprit.

If you can't login to disable them, you could rename your plugins folder. This will disable every plugin.

**Comment by hanne3w** [comment]
Thanks for your reply. Do you know how I can do this when I am not able to go on the webpage?

**Comment by tobiasschutter** [comment]
You could try connecting to your server through sFTP.
