### ISSUE TITLE
Exporting Empty Char

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#960]
Just a thought: in exporting we compare the value with the columns empty_char method and replace its value with '' when they are identical (===)

We could do two other things as well: 

- use a method in the Export Model that is also named empty_cell or empty_value 
- have a filter that enables or disables this (default) behaviour

**Comment by davidmosterd** [comment]
Only columns that use the AC_Column::get_value() can return an empty char. So the if statement to check the empty char is moved to the ACP_Export_Model_Value class, which checks this and has it's own get_empty_char() method to overwrite. On default it will return an empty string.

**Comment by davidmosterd** [comment]
Ticket is solved, but needs other tester. @DGStefan or @tobiasschutter

**Comment by tobiasschutter** [comment]
Tested
