### ISSUE TITLE
HTML entities on export

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#963]
If you run an export now, it will show things like &amp; instead of &

We should see if we can resolve these basic HTML entities to their UTF-8 form.

**Comment by davidmosterd** [comment]
We could try ```html_entity_decode($text, ENT_QUOTES, 'utf-8')```

**Comment by tobiasschutter** [comment]
I have implemented it

**Comment by davidmosterd** [comment]
@tobiasschutter The development branch is not coming along for 4.1, so if this was for 4.1 make sure you commit this ALSO (don't revert) to the release/4.1 branch.

**Comment by davidmosterd** [comment]
Has been merged into 4.1 now.
