### ISSUE TITLE
Export: support for 3rd party column values

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#968]
It would be nice if the export feature would also export custom defined columns that are added by other plugins. The challenge is to get the actual column values. Most values are printed, and can't easily be retrieved by using a getter. The `WP_List_Table` uses a `do_action( 'manage_posts_custom_column' )` to print the actual column values.

A solution might be to use output buffering. We would need to add an `add_action` with high priority so we can use `ob_start` and then another `add_action` with low priority and get the value with `ob_get_clean` and store the values in memory.

This example will output the column value on the page list table and buffers it for later use:
```
class ACPD_Issue_968 {

	const COLUMN = 'export_test';

	private $data;

	public function __construct() {
		// Register columns
		add_filter( 'manage_page_posts_columns', [ $this, 'add_column' ] );
		add_filter( 'manage_page_posts_custom_column', [ $this, 'column_value' ], 10, 2 );

		// Buffer value
		add_action( "manage_page_posts_custom_column", [ $this, 'ob_start' ], 1 );
		add_action( "manage_page_posts_custom_column", [ $this, 'ob_end' ], 1000, 2 );

		// Show debug
		add_action( "admin_footer", [ $this, 'display' ] );
	}

	public function add_column( $headings ) {
		$headings[ self::COLUMN ] = ucfirst( self::COLUMN );

		return $headings;
	}

	public function column_value( $column_name, $id ) {
		if ( self::COLUMN === $column_name ) {
			echo $id;
		}
	}

	public function ob_start( $column_name ) {
		if ( self::COLUMN === $column_name ) {
			ob_start();
		}
	}

	public function ob_end( $column_name, $id ) {
		if ( self::COLUMN === $column_name ) {
			$value = ob_get_clean();

			echo $value;

			$this->data[ $column_name ][ $id ] = $value;
		}
	}

	public function display() {
		echo '<pre>'; print_r( $this->data ); echo '</pre>'; exit;
	}

}

new ACPD_Issue_968;
```

**Comment by dglingren** [comment]
Thank you for opening this issue based on my email. As I wrote in a follow up message:

> I have already added inline editing to the MLA columns that seem appropriate, using the 'acp/column_types' action and the register_column_type function . It looks like I could define ACP_Export_Model objects and add export methods to return the appropriate values. Is that feasible?

How can I help?

**Comment by dglingren** [comment]
Your issue definition says:

> It would be nice if the export feature would also export custom defined columns that are added by other plugins.

It looks like you are referring to custom columns added to an existing WordPress submenu table, e.g., posts or pages. My original request was slightly different. My plugin uses the `WP_List_table` class to create a number of custom tables from scratch. How can I extend these tables to support export functions?

**Comment by tobiasschutter** [comment]
Added in ACP 5.1.3
