### ISSUE TITLE
WC Export: support missing

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#972]
- [x] ACA_WC_Column_Product_Attributes
- [x] ACA_WC_Column_ShopOrder_UserCustomField
- [x] ACA_WC_Column_ShopCoupon_Orders
- [x] ACA_WC_Column_ShopCoupon_EmailRestrictions
- [x] ACA_WC_Column_User_TotalSales
- [x] ACA_WC_Column_User_Orders

**Comment by DGStefan** [comment]
Closed in 
https://github.com/codepress/cac-addon-woocommerce/commit/7eb358fe48f0febd765258f5763d790eb8661e87
