### ISSUE TITLE
Exporting a date should try to comply to ISO-8601

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#973]
Currently, our date export (was discovered with ACF addon) can export like yyyymmdd. While very logical, yyyy-mm-dd would be better as it is an actual broad supported standard.

**Comment by davidmosterd** [comment]
Has a patch on the ACF addon branch.

It now uses the raw value. If it's not empty and 8 long it will add - between the yyyymmdd turning it into yyyy-mm-dd

What I DON'T like is the tampering with the raw value, which right now can't fall back on something if there is an error (like sending self::empty_char which the value export model can do)

@tobiasschutter @DGStefan Please test and opiniate.

**Comment by tobiasschutter** [comment]
Added numeric check. Let's merge this one.
