### ISSUE TITLE
Yoast SEO Score and Readability sortable

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#979]
Both columns are not sortable at the moment. 

`_yoast_wpseo_content_score` in the post_meta table contains each score per post.

Each column value is located in `WPSEO_Meta_Columns::column_content` which could also be used for sorting.

**Comment by davidmosterd** [comment]
https://github.com/codepress/admin-columns-pro/compare/979-yoast-seo-score-and-readability-sortable

Has patch. No longer extends from the baseclass of Yoast, but implements AC_Column_Meta. That does mean the group and original settings are duplicated. 

Hoewever, these two columns are sortable and have simpler export models (strippedrawvalue)

**Comment by davidmosterd** [comment]
@tobiasschutter @DGStefan can be tested

**Comment by tobiasschutter** [comment]
1. Values were being displayed twice. This is solved.
2. Tooltips are shown twice now for both columns. I created a new issue for this as it is not a blocker for this release. https://github.com/codepress/admin-columns-issues/issues/989
