### ISSUE TITLE
BuddyPress Groups column: Enable filtering for users with or without a group (empty/non empty)

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#981]

**Comment by DGStefan** [comment]
@davidmosterd 
Could have a look at the SQL query for filtering this column?
https://github.com/codepress/ac-addon-buddypress/commit/9a6dace27ee3ddb583f924c6294ce194ccb8d80e

**Comment by tobiasschutter** [comment]
Tested and approved
