### ISSUE TITLE
Events Calendar: Export keeps running and never finishes.

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#985]
When you go to the Events Calendar Events overview page and hit the export button, it starts running, but when the counter hits the max number, it just keeps running and goes over 100%.

**Comment by DGStefan** [comment]
@davidmosterd @tobiasschutter 
Implemented a custom Export ListScreen for Events that extends the default post-Listscreen where I remove the Events Calendar post_limits filter.

**Comment by tobiasschutter** [comment]
Fixed
