### ISSUE TITLE
Sorting on Meta column with all results

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#988]
When your sort on a native meta column (AC_Column_Meta) and you use "all results" options, it will generate an SQL error (not on your screen, but you won't have results)

It's a difficult issue to fix when you want to rely on the WP_Meta_Query (which is the power of the AC_Column_Meta) as it probably requires custom SQL.

**Comment by tobiasschutter** [comment]
Moved: https://github.com/codepress/admin-columns-pro/issues/349
