### ISSUE TITLE
New column: Share counter for Social Media

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#99]
A column with a share counter for each social media channel.

**Comment by engelen** [comment]
That's a great idea! This seems like addon territory to me, as it's focused around an external product.

**Comment by tobiasschutter** [comment]
I agree, this should not go into our core code. Also, most social platforms now need a form of authentication to retrieve statistics. There must be plugins that are already build for this. The only way we could support this is to extend a social plugin with our social columns. Any suggestions which plugins?

If we find such plugin I would suggest to populate the stats with ajax and cache them to prevent freezing posts overviews.
