### ISSUE TITLE
AC_Plugin and Updater

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#995]
The AC_Plugin should get a method called get_prefix() to have a uniform way to setup loading from it. Right now it's either hardcoded (AC_) or has a constant. Both are not predictable in behavior.

This could then lead to a cleaner way of running the installer:

```
	protected function install_updates( AC_Plugin $plugin ) {
		if ( 0 === version_compare( $plugin->get_version(), $plugin->get_stored_version() ) ) {
			return;
		}

		$classes = AC()->autoloader()->get_class_names_from_dir( $plugin->get_plugin_dir() . 'classes/Plugin/Update', $plugin->get_prefix() );
		$updater = new AC_Plugin_Updater( $plugin );

		foreach ( $classes as $class ) {
			$updater->add_update( new $class( $plugin->get_stored_version() ) );
		}

		$updater->parse_updates();
	}
```

**Comment by DGStefan** [comment]
This code was already present in our latest release.
I suspect this ticket still refers to the two todos in our code that points to #982 
We will change this when we need another update where we want to display the notices.
