### ISSUE TITLE
Non-Admins are seeing message to update Database

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#996]
There is no check that only admin may see this message.

**Comment by davidmosterd** [comment]
This is fixed, but was a bit more extensive than initially thought. I ended up adding a get_prefxi method to the AC_Plugin class and moved the process of applying updates to the AC_Plugin as well, since this is a very standardized process. So requires some testing.

**Comment by DGStefan** [comment]
Tested
